// Goethe A1 Wortliste - official word list for Start Deutsch 1
// Each entry: { w: word, a: article (der/die/das or ""), e: example sentence, c: category }

export const words = [
  // Zahlen
  { w: "eins", a: "", e: "Ich habe eins.", c: "Zahlen" },
  { w: "zwei", a: "", e: "Zwei Kaffee, bitte.", c: "Zahlen" },
  { w: "drei", a: "", e: "Ich habe drei Kinder.", c: "Zahlen" },
  { w: "vier", a: "", e: "Um vier Uhr.", c: "Zahlen" },
  { w: "fünf", a: "", e: "Fünf Euro, bitte.", c: "Zahlen" },
  { w: "sechs", a: "", e: "Sechs Uhr morgens.", c: "Zahlen" },
  { w: "sieben", a: "", e: "Sieben Tage die Woche.", c: "Zahlen" },
  { w: "acht", a: "", e: "Um acht Uhr beginnt der Kurs.", c: "Zahlen" },
  { w: "neun", a: "", e: "Neun Uhr.", c: "Zahlen" },
  { w: "zehn", a: "", e: "Zehn Euro.", c: "Zahlen" },
  { w: "zwanzig", a: "", e: "Ich bin zwanzig Jahre alt.", c: "Zahlen" },
  { w: "hundert", a: "", e: "Das kostet hundert Euro.", c: "Zahlen" },
  { w: "tausend", a: "", e: "Eintausend Kilometer.", c: "Zahlen" },

  // Zeit
  { w: "Sekunde", a: "die", e: "Einen Moment, eine Sekunde bitte.", c: "Zeit" },
  { w: "Minute", a: "die", e: "Der Zug kommt in fünf Minuten.", c: "Zeit" },
  { w: "Stunde", a: "die", e: "Ich bin in einer Stunde zurück.", c: "Zeit" },
  { w: "Tag", a: "der", e: "Heute ist ein schöner Tag.", c: "Zeit" },
  { w: "Woche", a: "die", e: "Sehen wir uns nächste Woche?", c: "Zeit" },
  { w: "Jahr", a: "das", e: "Ein gutes neues Jahr!", c: "Zeit" },
  { w: "Uhr", a: "die", e: "Es ist vier Uhr.", c: "Zeit" },
  { w: "Morgen", a: "der", e: "Guten Morgen!", c: "Zeit" },
  { w: "Vormittag", a: "der", e: "Am Vormittag arbeite ich.", c: "Zeit" },
  { w: "Mittag", a: "der", e: "Wir essen um zwölf Uhr Mittag.", c: "Zeit" },
  { w: "Nachmittag", a: "der", e: "Am Nachmittag bin ich frei.", c: "Zeit" },
  { w: "Abend", a: "der", e: "Guten Abend!", c: "Zeit" },
  { w: "Nacht", a: "die", e: "Gute Nacht!", c: "Zeit" },

  // Wochentage
  { w: "Montag", a: "der", e: "Am Montag beginnt der Kurs.", c: "Wochentage" },
  { w: "Dienstag", a: "der", e: "Dienstag habe ich frei.", c: "Wochentage" },
  { w: "Mittwoch", a: "der", e: "Am Mittwoch gehen wir einkaufen.", c: "Wochentage" },
  { w: "Donnerstag", a: "der", e: "Der Termin ist am Donnerstag.", c: "Wochentage" },
  { w: "Freitag", a: "der", e: "Am Freitag machen wir eine Party.", c: "Wochentage" },
  { w: "Samstag", a: "der", e: "Am Samstag schlafe ich lange.", c: "Wochentage" },
  { w: "Sonntag", a: "der", e: "Am Sonntag besuche ich meine Eltern.", c: "Wochentage" },
  { w: "Wochenende", a: "das", e: "Am Wochenende fahren wir weg.", c: "Wochentage" },

  // Monate
  { w: "Januar", a: "der", e: "Im Januar ist es kalt.", c: "Monate" },
  { w: "Februar", a: "der", e: "Im Februar schneit es oft.", c: "Monate" },
  { w: "März", a: "der", e: "Im März beginnt der Frühling.", c: "Monate" },
  { w: "April", a: "der", e: "Im April regnet es viel.", c: "Monate" },
  { w: "Mai", a: "der", e: "Im Mai blühen die Blumen.", c: "Monate" },
  { w: "Juni", a: "der", e: "Im Juni ist Sommer.", c: "Monate" },
  { w: "Juli", a: "der", e: "Im Juli fahren wir in Urlaub.", c: "Monate" },
  { w: "August", a: "der", e: "Im August ist es sehr heiß.", c: "Monate" },
  { w: "September", a: "der", e: "Im September beginnt die Schule.", c: "Monate" },
  { w: "Oktober", a: "der", e: "Im Oktober ist Oktoberfest.", c: "Monate" },
  { w: "November", a: "der", e: "Im November ist es dunkel.", c: "Monate" },
  { w: "Dezember", a: "der", e: "Im Dezember ist Weihnachten.", c: "Monate" },

  // Farben
  { w: "schwarz", a: "", e: "Der Kaffee ist schwarz.", c: "Farben" },
  { w: "weiß", a: "", e: "Die Wand ist weiß.", c: "Farben" },
  { w: "grau", a: "", e: "Der Himmel ist grau.", c: "Farben" },
  { w: "rot", a: "", e: "Die Tomate ist rot.", c: "Farben" },
  { w: "gelb", a: "", e: "Die Banane ist gelb.", c: "Farben" },
  { w: "blau", a: "", e: "Er hat blaue Augen.", c: "Farben" },
  { w: "grün", a: "", e: "Die Tomate ist noch grün.", c: "Farben" },
  { w: "braun", a: "", e: "Der Tisch ist braun.", c: "Farben" },

  // Person
  { w: "Name", a: "der", e: "Mein Name ist Thomas Schmidt.", c: "Person" },
  { w: "Vorname", a: "der", e: "Mein Vorname ist Eva.", c: "Person" },
  { w: "Adresse", a: "die", e: "Können Sie mir seine Adresse sagen?", c: "Person" },
  { w: "Alter", a: "das", e: "Alter: 26 Jahre.", c: "Person" },
  { w: "Geburtstag", a: "der", e: "Herzlichen Glückwunsch zum Geburtstag!", c: "Person" },
  { w: "Frau", a: "die", e: "Guten Tag, Frau Schmitt!", c: "Person" },
  { w: "Mann", a: "der", e: "Mein Mann arbeitet bei der Polizei.", c: "Person" },
  { w: "Kind", a: "das", e: "Wie viele Kinder haben Sie?", c: "Person" },
  { w: "Freund", a: "der", e: "Das ist ein Freund von mir.", c: "Person" },
  { w: "Familie", a: "die", e: "Meine Familie lebt in Spanien.", c: "Person" },
  { w: "Eltern", a: "die", e: "Meine Eltern leben in Spanien.", c: "Person" },
  { w: "Mutter", a: "die", e: "Das ist die Mutter von Michaela.", c: "Person" },
  { w: "Vater", a: "der", e: "Mein Vater ist Arbeiter.", c: "Person" },
  { w: "Sohn", a: "der", e: "Das ist Hans, mein Sohn.", c: "Person" },
  { w: "Tochter", a: "die", e: "Das ist meine Tochter Katharina.", c: "Person" },
  { w: "Bruder", a: "der", e: "Sein Bruder arbeitet auch hier.", c: "Person" },
  { w: "Schwester", a: "die", e: "Meine Schwester kommt am Dienstag.", c: "Person" },
  { w: "Großmutter", a: "die", e: "Meine Großmutter heißt Eva.", c: "Person" },
  { w: "Großvater", a: "der", e: "Mein Großvater ist schon 80.", c: "Person" },

  // Wohnen
  { w: "Wohnung", a: "die", e: "Seit wann haben Sie diese Wohnung?", c: "Wohnen" },
  { w: "Haus", a: "das", e: "In welchem Haus wohnst du?", c: "Wohnen" },
  { w: "Zimmer", a: "das", e: "Die Wohnung hat drei Zimmer.", c: "Wohnen" },
  { w: "Küche", a: "die", e: "Der neue Herd kommt in die Küche.", c: "Wohnen" },
  { w: "Bad", a: "das", e: "Wir haben kein großes Bad.", c: "Wohnen" },
  { w: "Balkon", a: "der", e: "Die Wohnung hat einen kleinen Balkon.", c: "Wohnen" },
  { w: "Garten", a: "der", e: "Wir haben leider keinen Garten.", c: "Wohnen" },
  { w: "Miete", a: "die", e: "Die Miete ist 600 Euro.", c: "Wohnen" },
  { w: "Möbel", a: "die", e: "Sind die Möbel neu?", c: "Wohnen" },
  { w: "Tisch", a: "der", e: "Die Fotos liegen auf dem Tisch.", c: "Wohnen" },
  { w: "Bett", a: "das", e: "Wir brauchen noch ein Kinderbett.", c: "Wohnen" },
  { w: "Schrank", a: "der", e: "Die Gläser stehen im Schrank.", c: "Wohnen" },
  { w: "Kühlschrank", a: "der", e: "Die Milch ist im Kühlschrank.", c: "Wohnen" },
  { w: "Schlüssel", a: "der", e: "Ich gebe Ihnen den Zimmerschlüssel.", c: "Wohnen" },
  { w: "Aufzug", a: "der", e: "Es gibt keinen Aufzug.", c: "Wohnen" },
  { w: "Treppe", a: "die", e: "Die Treppe hoch und dann links.", c: "Wohnen" },

  // Essen
  { w: "Essen", a: "das", e: "Das Essen ist heute sehr gut.", c: "Essen" },
  { w: "Frühstück", a: "das", e: "Möchtest du ein Ei zum Frühstück?", c: "Essen" },
  { w: "Kaffee", a: "der", e: "Zum Frühstück trinke ich immer Kaffee.", c: "Essen" },
  { w: "Tee", a: "der", e: "Ich trinke morgens immer Tee.", c: "Essen" },
  { w: "Milch", a: "die", e: "Die Milch steht im Kühlschrank.", c: "Essen" },
  { w: "Wasser", a: "das", e: "Ein Glas Wasser, bitte.", c: "Essen" },
  { w: "Bier", a: "das", e: "Noch ein Bier bitte.", c: "Essen" },
  { w: "Wein", a: "der", e: "Ich möchte keinen Wein.", c: "Essen" },
  { w: "Saft", a: "der", e: "Möchtest du einen Apfelsaft?", c: "Essen" },
  { w: "Brot", a: "das", e: "Haben Sie auch Weißbrot?", c: "Essen" },
  { w: "Brötchen", a: "das", e: "Möchtest du Brötchen zum Frühstück?", c: "Essen" },
  { w: "Butter", a: "die", e: "Ein Brötchen mit Butter und Käse.", c: "Essen" },
  { w: "Ei", a: "das", e: "Möchtest du ein Ei zum Frühstück?", c: "Essen" },
  { w: "Fleisch", a: "das", e: "Fleisch mag ich nicht.", c: "Essen" },
  { w: "Fisch", a: "der", e: "Ich esse gern Fisch.", c: "Essen" },
  { w: "Reis", a: "der", e: "Ich esse gern Reis.", c: "Essen" },
  { w: "Salat", a: "der", e: "Wie schmeckt dir der Salat?", c: "Essen" },
  { w: "Obst", a: "das", e: "Im Sommer ist das Obst billig.", c: "Essen" },
  { w: "Gemüse", a: "das", e: "Gemüse brauchen wir auch noch.", c: "Essen" },
  { w: "Kartoffel", a: "die", e: "Für Pommes braucht man Kartoffeln.", c: "Essen" },
  { w: "Tomate", a: "die", e: "Die Tomate ist noch grün.", c: "Essen" },
  { w: "Apfel", a: "der", e: "Ein Pfund Äpfel bitte.", c: "Essen" },
  { w: "Banane", a: "die", e: "Drei Bananen, bitte!", c: "Essen" },
  { w: "Kuchen", a: "der", e: "Ich nehme ein Stück Kuchen.", c: "Essen" },
  { w: "Hähnchen", a: "das", e: "Ein Hähnchen mit Pommes bitte!", c: "Essen" },
  { w: "Speisekarte", a: "die", e: "Die Speisekarte, bitte.", c: "Essen" },
  { w: "Rechnung", a: "die", e: "Die Rechnung, bitte.", c: "Essen" },
  { w: "Restaurant", a: "das", e: "Wir essen heute in einem Restaurant.", c: "Essen" },
  { w: "Café", a: "das", e: "Sollen wir uns im Café treffen?", c: "Essen" },

  // Einkaufen
  { w: "Geschäft", a: "das", e: "Die Geschäfte schließen um 18.30 Uhr.", c: "Einkaufen" },
  { w: "Laden", a: "der", e: "Im Buchladen können Sie Bücher kaufen.", c: "Einkaufen" },
  { w: "Kasse", a: "die", e: "Zahlen Sie bitte an der Kasse.", c: "Einkaufen" },
  { w: "Preis", a: "der", e: "Die Preise sind hoch.", c: "Einkaufen" },
  { w: "Geld", a: "das", e: "Hast du noch Geld?", c: "Einkaufen" },
  { w: "billig", a: "", e: "Die Jacke ist aber billig!", c: "Einkaufen" },
  { w: "teuer", a: "", e: "Das ist mir zu teuer.", c: "Einkaufen" },
  { w: "kaufen", a: "", e: "Tim kauft sich ein neues Auto.", c: "Einkaufen" },
  { w: "bezahlen", a: "", e: "Wo muss ich bezahlen?", c: "Einkaufen" },
  { w: "kosten", a: "", e: "Wie viel kostet das?", c: "Einkaufen" },

  // Reisen
  { w: "Bahnhof", a: "der", e: "Komme ich hier zum Bahnhof?", c: "Reisen" },
  { w: "Zug", a: "der", e: "Ich fahre gern mit dem Zug.", c: "Reisen" },
  { w: "Bus", a: "der", e: "Wann kommt der nächste Bus?", c: "Reisen" },
  { w: "S-Bahn", a: "die", e: "Ich nehme lieber die S-Bahn.", c: "Reisen" },
  { w: "Taxi", a: "das", e: "Er fährt mit dem Taxi.", c: "Reisen" },
  { w: "Auto", a: "das", e: "Er kommt mit dem Auto.", c: "Reisen" },
  { w: "Fahrrad", a: "das", e: "Fährst du mit dem Fahrrad?", c: "Reisen" },
  { w: "Flugzeug", a: "das", e: "Das Flugzeug kommt heute später an.", c: "Reisen" },
  { w: "Flughafen", a: "der", e: "Kannst du mich zum Flughafen bringen?", c: "Reisen" },
  { w: "Haltestelle", a: "die", e: "An der nächsten Haltestelle aussteigen.", c: "Reisen" },
  { w: "Fahrkarte", a: "die", e: "Hast du schon eine Fahrkarte?", c: "Reisen" },
  { w: "Ticket", a: "das", e: "Wie viel kostet das Ticket?", c: "Reisen" },
  { w: "Gepäck", a: "das", e: "Wollen Sie Ihr Gepäck mitnehmen?", c: "Reisen" },
  { w: "Koffer", a: "der", e: "Ist das Ihr Koffer?", c: "Reisen" },
  { w: "Hotel", a: "das", e: "Im Urlaub sind wir in einem Hotel.", c: "Reisen" },
  { w: "Reise", a: "die", e: "Wir machen eine Reise nach Österreich.", c: "Reisen" },
  { w: "Urlaub", a: "der", e: "Ich nehme im September Urlaub.", c: "Reisen" },
  { w: "Straße", a: "die", e: "In welcher Straße wohnen Sie?", c: "Reisen" },

  // Arbeit
  { w: "Arbeit", a: "die", e: "Mein Bruder sucht Arbeit.", c: "Arbeit" },
  { w: "arbeiten", a: "", e: "Wo arbeiten Sie?", c: "Arbeit" },
  { w: "Beruf", a: "der", e: "Was ist Ihr Beruf?", c: "Arbeit" },
  { w: "Job", a: "der", e: "Jenny hat einen neuen Job.", c: "Arbeit" },
  { w: "Firma", a: "die", e: "Er arbeitet bei einer Firma.", c: "Arbeit" },
  { w: "Chef", a: "der", e: "Wir haben eine neue Chefin.", c: "Arbeit" },
  { w: "Kollege", a: "der", e: "Wie heißt die neue Kollegin?", c: "Arbeit" },
  { w: "Lehrer", a: "der", e: "Unsere Lehrerin heißt Frau Müller.", c: "Arbeit" },
  { w: "Arzt", a: "der", e: "Ich habe einen Termin beim Arzt.", c: "Arbeit" },
  { w: "Student", a: "der", e: "Ich bin Studentin.", c: "Arbeit" },
  { w: "Termin", a: "der", e: "Machen wir sofort einen Termin.", c: "Arbeit" },

  // Lernen
  { w: "Schule", a: "die", e: "Meine Tochter geht in die Schule.", c: "Lernen" },
  { w: "Kurs", a: "der", e: "Der Deutschkurs geht bis zum Sommer.", c: "Lernen" },
  { w: "Unterricht", a: "der", e: "Unterricht von 8 bis 12 Uhr.", c: "Lernen" },
  { w: "Prüfung", a: "die", e: "Die Prüfung ist am Montag.", c: "Lernen" },
  { w: "Test", a: "der", e: "Der Test war einfach.", c: "Lernen" },
  { w: "lernen", a: "", e: "Wie lange lernen Sie schon Deutsch?", c: "Lernen" },
  { w: "Sprache", a: "die", e: "Welche Sprachen sprichst du?", c: "Lernen" },

  // Verben
  { w: "gehen", a: "", e: "Ich muss zum Arzt gehen.", c: "Verben" },
  { w: "kommen", a: "", e: "Woher kommen Sie?", c: "Verben" },
  { w: "fahren", a: "", e: "Ich fahre mit dem Auto zur Arbeit.", c: "Verben" },
  { w: "machen", a: "", e: "Was machst du heute Abend?", c: "Verben" },
  { w: "sprechen", a: "", e: "Kann ich mit Herrn Klein sprechen?", c: "Verben" },
  { w: "schreiben", a: "", e: "Er schreibt jeden Tag E-Mails.", c: "Verben" },
  { w: "lesen", a: "", e: "Ich lese ein Buch.", c: "Verben" },
  { w: "hören", a: "", e: "Hör mal! Was ist das?", c: "Verben" },
  { w: "sehen", a: "", e: "Ich kann dich nicht sehen.", c: "Verben" },
  { w: "essen", a: "", e: "Was gibt es zu essen?", c: "Verben" },
  { w: "trinken", a: "", e: "Möchtest du etwas trinken?", c: "Verben" },
  { w: "schlafen", a: "", e: "Ich schlafe acht Stunden.", c: "Verben" },
  { w: "wohnen", a: "", e: "Ich wohne in München.", c: "Verben" },
  { w: "helfen", a: "", e: "Können Sie mir helfen?", c: "Verben" },
  { w: "brauchen", a: "", e: "Brauchst du die Zeitung noch?", c: "Verben" },
  { w: "möchten", a: "", e: "Was möchten Sie trinken?", c: "Verben" },
  { w: "können", a: "", e: "Ich kann Deutsch und Russisch.", c: "Verben" },
  { w: "müssen", a: "", e: "Ich muss von 8 bis 18 Uhr arbeiten.", c: "Verben" },
  { w: "sollen", a: "", e: "Was soll ich mitbringen?", c: "Verben" },
  { w: "dürfen", a: "", e: "Sie dürfen hier nicht rauchen.", c: "Verben" },
  { w: "wollen", a: "", e: "Wollen Sie einen Kaffee?", c: "Verben" },
  { w: "kennen", a: "", e: "Kennen Sie diese Frau?", c: "Verben" },
  { w: "wissen", a: "", e: "Weißt du, wie er heißt?", c: "Verben" },
  { w: "nehmen", a: "", e: "Ich nehme den Bus.", c: "Verben" },
  { w: "geben", a: "", e: "Geben Sie mir bitte den Kugelschreiber.", c: "Verben" },
  { w: "stehen", a: "", e: "Der Bus steht an der Haltestelle.", c: "Verben" },
  { w: "kochen", a: "", e: "Herr Georgi kann gut kochen.", c: "Verben" },
  { w: "spielen", a: "", e: "Die Kinder spielen draußen.", c: "Verben" },
  { w: "schwimmen", a: "", e: "Ich schwimme jeden Tag.", c: "Verben" },
  { w: "beginnen", a: "", e: "Das Spiel beginnt um 15.30 Uhr.", c: "Verben" },
  { w: "aufstehen", a: "", e: "Ich muss um vier Uhr aufstehen.", c: "Verben" },
  { w: "anrufen", a: "", e: "Kann man Sie anrufen?", c: "Verben" },
  { w: "einkaufen", a: "", e: "Ich muss noch einkaufen.", c: "Verben" },
  { w: "verstehen", a: "", e: "Können Sie mich verstehen?", c: "Verben" },

  // Adjektive
  { w: "gut", a: "", e: "Das finde ich gut.", c: "Adjektive" },
  { w: "schlecht", a: "", e: "Mir ist schlecht!", c: "Adjektive" },
  { w: "schön", a: "", e: "Das ist sehr schön.", c: "Adjektive" },
  { w: "groß", a: "", e: "Frankfurt ist eine große Stadt.", c: "Adjektive" },
  { w: "klein", a: "", e: "Eltville ist eine kleine Stadt.", c: "Adjektive" },
  { w: "alt", a: "", e: "Wie alt sind Sie?", c: "Adjektive" },
  { w: "neu", a: "", e: "Ich bin der neue Kollege.", c: "Adjektive" },
  { w: "jung", a: "", e: "Noch so jung?", c: "Adjektive" },
  { w: "schnell", a: "", e: "Er fährt schnell.", c: "Adjektive" },
  { w: "langsam", a: "", e: "Bitte etwas langsamer sprechen.", c: "Adjektive" },
  { w: "leicht", a: "", e: "Der Koffer ist leicht.", c: "Adjektive" },
  { w: "schwer", a: "", e: "Ist Ihr Gepäck sehr schwer?", c: "Adjektive" },
  { w: "krank", a: "", e: "Ich bin krank.", c: "Adjektive" },
  { w: "müde", a: "", e: "Ich bin müde.", c: "Adjektive" },
  { w: "frei", a: "", e: "Ist der Platz noch frei?", c: "Adjektive" },
  { w: "richtig", a: "", e: "Das ist richtig.", c: "Adjektive" },
  { w: "falsch", a: "", e: "Das ist falsch.", c: "Adjektive" },
  { w: "einfach", a: "", e: "Die Prüfung ist ganz einfach.", c: "Adjektive" },
  { w: "wichtig", a: "", e: "Dieses Formular ist sehr wichtig.", c: "Adjektive" },
  { w: "kaputt", a: "", e: "Das Glas ist kaputt.", c: "Adjektive" },
  { w: "fertig", a: "", e: "Bist du fertig?", c: "Adjektive" },
  { w: "laut", a: "", e: "Nicht so laut! Das Baby schläft.", c: "Adjektive" },
  { w: "ruhig", a: "", e: "Ich möchte ein ruhiges Zimmer.", c: "Adjektive" },

  // Kommunikation
  { w: "Hallo", a: "", e: "Hallo! Wie geht's?", c: "Kommunikation" },
  { w: "Guten Morgen", a: "", e: "Guten Morgen!", c: "Kommunikation" },
  { w: "Guten Tag", a: "", e: "Guten Tag, Herr Sommer!", c: "Kommunikation" },
  { w: "Auf Wiedersehen", a: "", e: "Auf Wiedersehen!", c: "Kommunikation" },
  { w: "Tschüss", a: "", e: "Tschüss! Bis morgen!", c: "Kommunikation" },
  { w: "Danke", a: "", e: "Vielen Dank!", c: "Kommunikation" },
  { w: "Bitte", a: "", e: "Eine Tasse Kaffee, bitte!", c: "Kommunikation" },
  { w: "Entschuldigung", a: "die", e: "Entschuldigung! – Bitte.", c: "Kommunikation" },
  { w: "ja", a: "", e: "Ja.", c: "Kommunikation" },
  { w: "nein", a: "", e: "Nein, ich habe keine Zeit.", c: "Kommunikation" },
  { w: "Hilfe", a: "die", e: "Hilfe! Bitte helfen Sie mir!", c: "Kommunikation" },

  // Orte
  { w: "Stadt", a: "die", e: "Heidelberg ist eine alte Stadt.", c: "Orte" },
  { w: "Post", a: "die", e: "Wo ist die Post, bitte?", c: "Orte" },
  { w: "Bank", a: "die", e: "Die Bank schließt um vier Uhr.", c: "Orte" },
  { w: "Polizei", a: "die", e: "Holen Sie die Polizei!", c: "Orte" },
  { w: "Kino", a: "das", e: "Wir sehen im Kino einen Film.", c: "Orte" },
  { w: "Bäckerei", a: "die", e: "Ich geh zur Bäckerei.", c: "Orte" },
  { w: "Kindergarten", a: "der", e: "Laura geht in den Kindergarten.", c: "Orte" },
  { w: "Schwimmbad", a: "das", e: "Kommst du mit ins Schwimmbad?", c: "Orte" },

  // Gesundheit
  { w: "Kopf", a: "der", e: "Mein Kopf tut weh!", c: "Gesundheit" },
  { w: "Auge", a: "das", e: "Er hat blaue Augen.", c: "Gesundheit" },
  { w: "Hand", a: "die", e: "Er gibt mir die Hand.", c: "Gesundheit" },
  { w: "Arm", a: "der", e: "Mein Arm tut weh.", c: "Gesundheit" },
  { w: "Bein", a: "das", e: "Mein rechtes Bein tut weh.", c: "Gesundheit" },
  { w: "Fuß", a: "der", e: "Der linke Fuß tut mir weh.", c: "Gesundheit" },
  { w: "Bauch", a: "der", e: "Mein Bauch tut weh.", c: "Gesundheit" },
  { w: "Hunger", a: "der", e: "Ich habe Hunger!", c: "Gesundheit" },
  { w: "Durst", a: "der", e: "Ich habe großen Durst.", c: "Gesundheit" },
  { w: "Doktor", a: "der", e: "Wir gehen zum Doktor.", c: "Gesundheit" },

  // Technik
  { w: "Telefon", a: "das", e: "Haben Sie Telefon?", c: "Technik" },
  { w: "Handy", a: "das", e: "Bitte die Handys ausmachen!", c: "Technik" },
  { w: "Computer", a: "der", e: "Wann bekommst du deinen Computer?", c: "Technik" },
  { w: "Internet", a: "das", e: "Das findest du im Internet.", c: "Technik" },
  { w: "E-Mail", a: "die", e: "Ich habe Ihre E-Mail nicht bekommen.", c: "Technik" },
  { w: "Brief", a: "der", e: "Haben Sie einen Brief für mich?", c: "Technik" },
  { w: "Zeitung", a: "die", e: "Ich lese gern Zeitung.", c: "Technik" },
  { w: "Foto", a: "das", e: "Darf ich ein Foto machen?", c: "Technik" },
  { w: "Buch", a: "das", e: "Gute Bücher sind oft teuer.", c: "Technik" },

  // Kleidung
  { w: "Kleidung", a: "die", e: "Wo finde ich Kleidung?", c: "Kleidung" },
  { w: "Jacke", a: "die", e: "Zieh dir eine Jacke an!", c: "Kleidung" },
  { w: "Schuh", a: "der", e: "Zieh die Schuhe aus!", c: "Kleidung" },

  // Wetter
  { w: "Wetter", a: "das", e: "Wir hatten schlechtes Wetter.", c: "Wetter" },
  { w: "Regen", a: "der", e: "Bei diesem Regen gehe ich nicht raus.", c: "Wetter" },
  { w: "Sonne", a: "die", e: "Die Sonne scheint.", c: "Wetter" },
  { w: "kalt", a: "", e: "Mir ist kalt.", c: "Wetter" },
  { w: "warm", a: "", e: "Es ist warm heute.", c: "Wetter" },

  // Sonstiges
  { w: "aber", a: "", e: "Ich bin oft im Büro, aber nur kurz.", c: "Sonstiges" },
  { w: "auch", a: "", e: "Ich bin auch Spanier.", c: "Sonstiges" },
  { w: "dann", a: "", e: "Erst zur Post, dann komme ich.", c: "Sonstiges" },
  { w: "gern(e)", a: "", e: "Ich gehe gerne einkaufen.", c: "Sonstiges" },
  { w: "heute", a: "", e: "Heute ist ein schöner Tag.", c: "Sonstiges" },
  { w: "hier", a: "", e: "Hier wohne ich.", c: "Sonstiges" },
  { w: "immer", a: "", e: "Sie kommt immer zu spät.", c: "Sonstiges" },
  { w: "jetzt", a: "", e: "Jetzt machen wir Pause.", c: "Sonstiges" },
  { w: "morgen", a: "", e: "Morgen beginnt die Schule.", c: "Sonstiges" },
  { w: "gestern", a: "", e: "Gestern war ich krank.", c: "Sonstiges" },
  { w: "nicht", a: "", e: "Das stimmt nicht.", c: "Sonstiges" },
  { w: "noch", a: "", e: "Wir warten noch fünf Minuten.", c: "Sonstiges" },
  { w: "nur", a: "", e: "Ich möchte nur ein Glas Wasser.", c: "Sonstiges" },
  { w: "sehr", a: "", e: "Danke sehr!", c: "Sonstiges" },
  { w: "viel", a: "", e: "Hier regnet es viel.", c: "Sonstiges" },
  { w: "zusammen", a: "", e: "Sollen wir zusammen essen gehen?", c: "Sonstiges" },
  { w: "rechts", a: "", e: "Die Straße ist hier rechts.", c: "Sonstiges" },
  { w: "links", a: "", e: "Gehen Sie die nächste Straße links.", c: "Sonstiges" },
  { w: "geradeaus", a: "", e: "Gehen Sie immer geradeaus!", c: "Sonstiges" },
  { w: "Deutschland", a: "", e: "Ich wohne in Deutschland.", c: "Sonstiges" },
  { w: "Formular", a: "das", e: "Füllen Sie dieses Formular aus.", c: "Sonstiges" },
  { w: "Ausweis", a: "der", e: "Hier ist mein Ausweis.", c: "Sonstiges" },
  { w: "Hobby", a: "das", e: "Meine Hobbys sind Wandern und Schwimmen.", c: "Sonstiges" },
  { w: "Sport", a: "der", e: "Ich mache viel Sport.", c: "Sonstiges" },
  { w: "Fußball", a: "der", e: "Spielt ihr gerne Fußball?", c: "Sonstiges" },
  { w: "Geschenk", a: "das", e: "Danke für das schöne Geschenk.", c: "Sonstiges" },
  { w: "Einladung", a: "die", e: "Danke für die Einladung!", c: "Sonstiges" },
];

export const emailPrompts = [
  "Invite a friend to your birthday party on Saturday at 7 PM.",
  "Cancel a doctor's appointment on Monday.",
  "Ask about a German course: when, how much?",
  "Write to your landlord: the heating is broken.",
  "Thank a friend for a gift.",
  "Ask about exam registration.",
  "Invite a colleague for coffee.",
  "Your child is sick, inform the school.",
  "Ask about swimming pool hours.",
  "Apologize for being late.",
  "Book a hotel room for two nights.",
  "Tell a friend about your new apartment.",
];

export const wfQuestions = [
  { q: "___ heißen Sie?", a: "Wie", o: ["Wo", "Wie", "Was", "Wann"] },
  { q: "___ wohnen Sie?", a: "Wo", o: ["Wer", "Was", "Wo", "Warum"] },
  { q: "___ kommen Sie?", a: "Woher", o: ["Woher", "Wohin", "Wo", "Wann"] },
  { q: "___ beginnt der Kurs?", a: "Wann", o: ["Was", "Wo", "Wann", "Wer"] },
  { q: "___ kostet das?", a: "Wie viel", o: ["Was", "Wie viel", "Wann", "Wo"] },
  { q: "___ ist das?", a: "Wer", o: ["Wer", "Wo", "Was", "Wie"] },
  { q: "___ lernst du Deutsch?", a: "Warum", o: ["Wann", "Warum", "Wie", "Wo"] },
  { q: "___ fährst du am Wochenende?", a: "Wohin", o: ["Woher", "Wo", "Wann", "Wohin"] },
  { q: "___ Sprachen sprechen Sie?", a: "Welche", o: ["Was", "Welche", "Wie", "Wann"] },
  { q: "___ alt sind Sie?", a: "Wie", o: ["Was", "Wo", "Wie", "Wer"] },
  { q: "___ machst du heute?", a: "Was", o: ["Wer", "Was", "Wo", "Wann"] },
  { q: "___ geht es Ihnen?", a: "Wie", o: ["Wie", "Was", "Wo", "Wer"] },
  { q: "___ kommt der nächste Bus?", a: "Wann", o: ["Wo", "Wann", "Was", "Wer"] },
  { q: "___ ist die Toilette?", a: "Wo", o: ["Was", "Wer", "Wo", "Wie"] },
  { q: "___ möchten Sie trinken?", a: "Was", o: ["Wie", "Was", "Wo", "Wer"] },
  { q: "___ Kinder haben Sie?", a: "Wie viele", o: ["Was", "Wann", "Wie viele", "Welche"] },
  { q: "___ ist Ihr Beruf?", a: "Was", o: ["Wer", "Was", "Wie", "Wann"] },
  { q: "___ Buch möchtest du?", a: "Welches", o: ["Was", "Welches", "Wie", "Wo"] },
  { q: "___ kommt er nicht?", a: "Warum", o: ["Wann", "Warum", "Wie", "Wo"] },
];

export const schedule = [
  { d: 1, f: "Decoding", t: "Go through flashcards. Mark words you don't know." },
  { d: 2, f: "Decoding", t: "Continue flashcards. Focus on 'Don't Know' words." },
  { d: 3, f: "Decoding", t: "Final pass through unknown words. Use Word List to review." },
  { d: 4, f: "Patterns", t: "Study Grammar tab. Watch A1 Speaking Exam videos on YouTube." },
  { d: 5, f: "Patterns", t: "Practice Speaking Simulator. Note exact phrases." },
  { d: 6, f: "Patterns", t: "Master W-Fragen quiz. Review email templates." },
  { d: 7, f: "Simulations", t: "Do practice test set 1 (Goethe website). Time yourself." },
  { d: 8, f: "Simulations", t: "Do practice test set 2. Review mistakes." },
  { d: 9, f: "Simulations", t: "Do practice test set 3. Focus on listening (catch the nouns!)." },
  { d: 10, f: "Simulations", t: "Review all wrong answers. Drill weak categories." },
  { d: 11, f: "Production", t: "Write 2 practice emails. Self-Intro 5 times." },
  { d: 12, f: "Production", t: "Write 2 more emails. Self-Intro 5 more times. Speaking cards." },
  { d: 13, f: "Production", t: "Final email. Self-Intro 10 times. Full speaking run-through." },
  { d: 14, f: "Rest", t: "Review Grammar cheat sheet & email templates only. You got this." },
];
