// Goethe A1 Wortliste - official word list for Start Deutsch 1
// Each entry: { w: word, a: article (der/die/das or ""), e: example sentence, t: English translation, c: category }

export const words = [
  // Zahlen
  { w: "eins", a: "", e: "Ich habe eins.", t: "one", c: "Zahlen" },
  { w: "zwei", a: "", e: "Zwei Kaffee, bitte.", t: "two", c: "Zahlen" },
  { w: "drei", a: "", e: "Ich habe drei Kinder.", t: "three", c: "Zahlen" },
  { w: "vier", a: "", e: "Um vier Uhr.", t: "four", c: "Zahlen" },
  { w: "fünf", a: "", e: "Fünf Euro, bitte.", t: "five", c: "Zahlen" },
  { w: "sechs", a: "", e: "Sechs Uhr morgens.", t: "six", c: "Zahlen" },
  { w: "sieben", a: "", e: "Sieben Tage die Woche.", t: "seven", c: "Zahlen" },
  { w: "acht", a: "", e: "Um acht Uhr beginnt der Kurs.", t: "eight", c: "Zahlen" },
  { w: "neun", a: "", e: "Neun Uhr.", t: "nine", c: "Zahlen" },
  { w: "zehn", a: "", e: "Zehn Euro.", t: "ten", c: "Zahlen" },
  { w: "zwanzig", a: "", e: "Ich bin zwanzig Jahre alt.", t: "twenty", c: "Zahlen" },
  { w: "hundert", a: "", e: "Das kostet hundert Euro.", t: "hundred", c: "Zahlen" },
  { w: "tausend", a: "", e: "Eintausend Kilometer.", t: "thousand", c: "Zahlen" },

  // Zeit
  { w: "Sekunde", a: "die", e: "Einen Moment, eine Sekunde bitte.", t: "second", c: "Zeit" },
  { w: "Minute", a: "die", e: "Der Zug kommt in fünf Minuten.", t: "minute", c: "Zeit" },
  { w: "Stunde", a: "die", e: "Ich bin in einer Stunde zurück.", t: "hour", c: "Zeit" },
  { w: "Tag", a: "der", e: "Heute ist ein schöner Tag.", t: "day", c: "Zeit" },
  { w: "Woche", a: "die", e: "Sehen wir uns nächste Woche?", t: "week", c: "Zeit" },
  { w: "Jahr", a: "das", e: "Ein gutes neues Jahr!", t: "year", c: "Zeit" },
  { w: "Uhr", a: "die", e: "Es ist vier Uhr.", t: "clock / o'clock", c: "Zeit" },
  { w: "Morgen", a: "der", e: "Guten Morgen!", t: "morning", c: "Zeit" },
  { w: "Vormittag", a: "der", e: "Am Vormittag arbeite ich.", t: "late morning", c: "Zeit" },
  { w: "Mittag", a: "der", e: "Wir essen um zwölf Uhr Mittag.", t: "noon / midday", c: "Zeit" },
  { w: "Nachmittag", a: "der", e: "Am Nachmittag bin ich frei.", t: "afternoon", c: "Zeit" },
  { w: "Abend", a: "der", e: "Guten Abend!", t: "evening", c: "Zeit" },
  { w: "Nacht", a: "die", e: "Gute Nacht!", t: "night", c: "Zeit" },

  // Wochentage
  { w: "Montag", a: "der", e: "Am Montag beginnt der Kurs.", t: "Monday", c: "Wochentage" },
  { w: "Dienstag", a: "der", e: "Dienstag habe ich frei.", t: "Tuesday", c: "Wochentage" },
  { w: "Mittwoch", a: "der", e: "Am Mittwoch gehen wir einkaufen.", t: "Wednesday", c: "Wochentage" },
  { w: "Donnerstag", a: "der", e: "Der Termin ist am Donnerstag.", t: "Thursday", c: "Wochentage" },
  { w: "Freitag", a: "der", e: "Am Freitag machen wir eine Party.", t: "Friday", c: "Wochentage" },
  { w: "Samstag", a: "der", e: "Am Samstag schlafe ich lange.", t: "Saturday", c: "Wochentage" },
  { w: "Sonntag", a: "der", e: "Am Sonntag besuche ich meine Eltern.", t: "Sunday", c: "Wochentage" },
  { w: "Wochenende", a: "das", e: "Am Wochenende fahren wir weg.", t: "weekend", c: "Wochentage" },

  // Monate
  { w: "Januar", a: "der", e: "Im Januar ist es kalt.", t: "January", c: "Monate" },
  { w: "Februar", a: "der", e: "Im Februar schneit es oft.", t: "February", c: "Monate" },
  { w: "März", a: "der", e: "Im März beginnt der Frühling.", t: "March", c: "Monate" },
  { w: "April", a: "der", e: "Im April regnet es viel.", t: "April", c: "Monate" },
  { w: "Mai", a: "der", e: "Im Mai blühen die Blumen.", t: "May", c: "Monate" },
  { w: "Juni", a: "der", e: "Im Juni ist Sommer.", t: "June", c: "Monate" },
  { w: "Juli", a: "der", e: "Im Juli fahren wir in Urlaub.", t: "July", c: "Monate" },
  { w: "August", a: "der", e: "Im August ist es sehr heiß.", t: "August", c: "Monate" },
  { w: "September", a: "der", e: "Im September beginnt die Schule.", t: "September", c: "Monate" },
  { w: "Oktober", a: "der", e: "Im Oktober ist Oktoberfest.", t: "October", c: "Monate" },
  { w: "November", a: "der", e: "Im November ist es dunkel.", t: "November", c: "Monate" },
  { w: "Dezember", a: "der", e: "Im Dezember ist Weihnachten.", t: "December", c: "Monate" },

  // Farben
  { w: "schwarz", a: "", e: "Der Kaffee ist schwarz.", t: "black", c: "Farben" },
  { w: "weiß", a: "", e: "Die Wand ist weiß.", t: "white", c: "Farben" },
  { w: "grau", a: "", e: "Der Himmel ist grau.", t: "gray", c: "Farben" },
  { w: "rot", a: "", e: "Die Tomate ist rot.", t: "red", c: "Farben" },
  { w: "gelb", a: "", e: "Die Banane ist gelb.", t: "yellow", c: "Farben" },
  { w: "blau", a: "", e: "Er hat blaue Augen.", t: "blue", c: "Farben" },
  { w: "grün", a: "", e: "Die Tomate ist noch grün.", t: "green", c: "Farben" },
  { w: "braun", a: "", e: "Der Tisch ist braun.", t: "brown", c: "Farben" },

  // Person
  { w: "Name", a: "der", e: "Mein Name ist Thomas Schmidt.", t: "name", c: "Person" },
  { w: "Vorname", a: "der", e: "Mein Vorname ist Eva.", t: "first name", c: "Person" },
  { w: "Adresse", a: "die", e: "Können Sie mir seine Adresse sagen?", t: "address", c: "Person" },
  { w: "Alter", a: "das", e: "Alter: 26 Jahre.", t: "age", c: "Person" },
  { w: "Geburtstag", a: "der", e: "Herzlichen Glückwunsch zum Geburtstag!", t: "birthday", c: "Person" },
  { w: "Frau", a: "die", e: "Guten Tag, Frau Schmitt!", t: "woman / Mrs.", c: "Person" },
  { w: "Mann", a: "der", e: "Mein Mann arbeitet bei der Polizei.", t: "man / husband", c: "Person" },
  { w: "Kind", a: "das", e: "Wie viele Kinder haben Sie?", t: "child", c: "Person" },
  { w: "Freund", a: "der", e: "Das ist ein Freund von mir.", t: "friend", c: "Person" },
  { w: "Familie", a: "die", e: "Meine Familie lebt in Spanien.", t: "family", c: "Person" },
  { w: "Eltern", a: "die", e: "Meine Eltern leben in Spanien.", t: "parents", c: "Person" },
  { w: "Mutter", a: "die", e: "Das ist die Mutter von Michaela.", t: "mother", c: "Person" },
  { w: "Vater", a: "der", e: "Mein Vater ist Arbeiter.", t: "father", c: "Person" },
  { w: "Sohn", a: "der", e: "Das ist Hans, mein Sohn.", t: "son", c: "Person" },
  { w: "Tochter", a: "die", e: "Das ist meine Tochter Katharina.", t: "daughter", c: "Person" },
  { w: "Bruder", a: "der", e: "Sein Bruder arbeitet auch hier.", t: "brother", c: "Person" },
  { w: "Schwester", a: "die", e: "Meine Schwester kommt am Dienstag.", t: "sister", c: "Person" },
  { w: "Großmutter", a: "die", e: "Meine Großmutter heißt Eva.", t: "grandmother", c: "Person" },
  { w: "Großvater", a: "der", e: "Mein Großvater ist schon 80.", t: "grandfather", c: "Person" },

  // Wohnen
  { w: "Wohnung", a: "die", e: "Seit wann haben Sie diese Wohnung?", t: "apartment", c: "Wohnen" },
  { w: "Haus", a: "das", e: "In welchem Haus wohnst du?", t: "house", c: "Wohnen" },
  { w: "Zimmer", a: "das", e: "Die Wohnung hat drei Zimmer.", t: "room", c: "Wohnen" },
  { w: "Küche", a: "die", e: "Der neue Herd kommt in die Küche.", t: "kitchen", c: "Wohnen" },
  { w: "Bad", a: "das", e: "Wir haben kein großes Bad.", t: "bathroom", c: "Wohnen" },
  { w: "Balkon", a: "der", e: "Die Wohnung hat einen kleinen Balkon.", t: "balcony", c: "Wohnen" },
  { w: "Garten", a: "der", e: "Wir haben leider keinen Garten.", t: "garden", c: "Wohnen" },
  { w: "Miete", a: "die", e: "Die Miete ist 600 Euro.", t: "rent", c: "Wohnen" },
  { w: "Möbel", a: "die", e: "Sind die Möbel neu?", t: "furniture", c: "Wohnen" },
  { w: "Tisch", a: "der", e: "Die Fotos liegen auf dem Tisch.", t: "table", c: "Wohnen" },
  { w: "Bett", a: "das", e: "Wir brauchen noch ein Kinderbett.", t: "bed", c: "Wohnen" },
  { w: "Schrank", a: "der", e: "Die Gläser stehen im Schrank.", t: "wardrobe / cupboard", c: "Wohnen" },
  { w: "Kühlschrank", a: "der", e: "Die Milch ist im Kühlschrank.", t: "refrigerator", c: "Wohnen" },
  { w: "Schlüssel", a: "der", e: "Ich gebe Ihnen den Zimmerschlüssel.", t: "key", c: "Wohnen" },
  { w: "Aufzug", a: "der", e: "Es gibt keinen Aufzug.", t: "elevator", c: "Wohnen" },
  { w: "Treppe", a: "die", e: "Die Treppe hoch und dann links.", t: "stairs", c: "Wohnen" },

  // Essen
  { w: "Essen", a: "das", e: "Das Essen ist heute sehr gut.", t: "food / meal", c: "Essen" },
  { w: "Frühstück", a: "das", e: "Möchtest du ein Ei zum Frühstück?", t: "breakfast", c: "Essen" },
  { w: "Kaffee", a: "der", e: "Zum Frühstück trinke ich immer Kaffee.", t: "coffee", c: "Essen" },
  { w: "Tee", a: "der", e: "Ich trinke morgens immer Tee.", t: "tea", c: "Essen" },
  { w: "Milch", a: "die", e: "Die Milch steht im Kühlschrank.", t: "milk", c: "Essen" },
  { w: "Wasser", a: "das", e: "Ein Glas Wasser, bitte.", t: "water", c: "Essen" },
  { w: "Bier", a: "das", e: "Noch ein Bier bitte.", t: "beer", c: "Essen" },
  { w: "Wein", a: "der", e: "Ich möchte keinen Wein.", t: "wine", c: "Essen" },
  { w: "Saft", a: "der", e: "Möchtest du einen Apfelsaft?", t: "juice", c: "Essen" },
  { w: "Brot", a: "das", e: "Haben Sie auch Weißbrot?", t: "bread", c: "Essen" },
  { w: "Brötchen", a: "das", e: "Möchtest du Brötchen zum Frühstück?", t: "bread roll", c: "Essen" },
  { w: "Butter", a: "die", e: "Ein Brötchen mit Butter und Käse.", t: "butter", c: "Essen" },
  { w: "Ei", a: "das", e: "Möchtest du ein Ei zum Frühstück?", t: "egg", c: "Essen" },
  { w: "Fleisch", a: "das", e: "Fleisch mag ich nicht.", t: "meat", c: "Essen" },
  { w: "Fisch", a: "der", e: "Ich esse gern Fisch.", t: "fish", c: "Essen" },
  { w: "Reis", a: "der", e: "Ich esse gern Reis.", t: "rice", c: "Essen" },
  { w: "Salat", a: "der", e: "Wie schmeckt dir der Salat?", t: "salad", c: "Essen" },
  { w: "Obst", a: "das", e: "Im Sommer ist das Obst billig.", t: "fruit", c: "Essen" },
  { w: "Gemüse", a: "das", e: "Gemüse brauchen wir auch noch.", t: "vegetables", c: "Essen" },
  { w: "Kartoffel", a: "die", e: "Für Pommes braucht man Kartoffeln.", t: "potato", c: "Essen" },
  { w: "Tomate", a: "die", e: "Die Tomate ist noch grün.", t: "tomato", c: "Essen" },
  { w: "Apfel", a: "der", e: "Ein Pfund Äpfel bitte.", t: "apple", c: "Essen" },
  { w: "Banane", a: "die", e: "Drei Bananen, bitte!", t: "banana", c: "Essen" },
  { w: "Kuchen", a: "der", e: "Ich nehme ein Stück Kuchen.", t: "cake", c: "Essen" },
  { w: "Hähnchen", a: "das", e: "Ein Hähnchen mit Pommes bitte!", t: "chicken", c: "Essen" },
  { w: "Speisekarte", a: "die", e: "Die Speisekarte, bitte.", t: "menu", c: "Essen" },
  { w: "Rechnung", a: "die", e: "Die Rechnung, bitte.", t: "bill / check", c: "Essen" },
  { w: "Restaurant", a: "das", e: "Wir essen heute in einem Restaurant.", t: "restaurant", c: "Essen" },
  { w: "Café", a: "das", e: "Sollen wir uns im Café treffen?", t: "café", c: "Essen" },

  // Einkaufen
  { w: "Geschäft", a: "das", e: "Die Geschäfte schließen um 18.30 Uhr.", t: "shop / store", c: "Einkaufen" },
  { w: "Laden", a: "der", e: "Im Buchladen können Sie Bücher kaufen.", t: "store / shop", c: "Einkaufen" },
  { w: "Kasse", a: "die", e: "Zahlen Sie bitte an der Kasse.", t: "cash register / checkout", c: "Einkaufen" },
  { w: "Preis", a: "der", e: "Die Preise sind hoch.", t: "price", c: "Einkaufen" },
  { w: "Geld", a: "das", e: "Hast du noch Geld?", t: "money", c: "Einkaufen" },
  { w: "billig", a: "", e: "Die Jacke ist aber billig!", t: "cheap", c: "Einkaufen" },
  { w: "teuer", a: "", e: "Das ist mir zu teuer.", t: "expensive", c: "Einkaufen" },
  { w: "kaufen", a: "", e: "Tim kauft sich ein neues Auto.", t: "to buy", c: "Einkaufen" },
  { w: "bezahlen", a: "", e: "Wo muss ich bezahlen?", t: "to pay", c: "Einkaufen" },
  { w: "kosten", a: "", e: "Wie viel kostet das?", t: "to cost", c: "Einkaufen" },

  // Reisen
  { w: "Bahnhof", a: "der", e: "Komme ich hier zum Bahnhof?", t: "train station", c: "Reisen" },
  { w: "Zug", a: "der", e: "Ich fahre gern mit dem Zug.", t: "train", c: "Reisen" },
  { w: "Bus", a: "der", e: "Wann kommt der nächste Bus?", t: "bus", c: "Reisen" },
  { w: "S-Bahn", a: "die", e: "Ich nehme lieber die S-Bahn.", t: "city train / metro", c: "Reisen" },
  { w: "Taxi", a: "das", e: "Er fährt mit dem Taxi.", t: "taxi", c: "Reisen" },
  { w: "Auto", a: "das", e: "Er kommt mit dem Auto.", t: "car", c: "Reisen" },
  { w: "Fahrrad", a: "das", e: "Fährst du mit dem Fahrrad?", t: "bicycle", c: "Reisen" },
  { w: "Flugzeug", a: "das", e: "Das Flugzeug kommt heute später an.", t: "airplane", c: "Reisen" },
  { w: "Flughafen", a: "der", e: "Kannst du mich zum Flughafen bringen?", t: "airport", c: "Reisen" },
  { w: "Haltestelle", a: "die", e: "An der nächsten Haltestelle aussteigen.", t: "bus stop", c: "Reisen" },
  { w: "Fahrkarte", a: "die", e: "Hast du schon eine Fahrkarte?", t: "ticket", c: "Reisen" },
  { w: "Ticket", a: "das", e: "Wie viel kostet das Ticket?", t: "ticket", c: "Reisen" },
  { w: "Gepäck", a: "das", e: "Wollen Sie Ihr Gepäck mitnehmen?", t: "luggage", c: "Reisen" },
  { w: "Koffer", a: "der", e: "Ist das Ihr Koffer?", t: "suitcase", c: "Reisen" },
  { w: "Hotel", a: "das", e: "Im Urlaub sind wir in einem Hotel.", t: "hotel", c: "Reisen" },
  { w: "Reise", a: "die", e: "Wir machen eine Reise nach Österreich.", t: "trip / journey", c: "Reisen" },
  { w: "Urlaub", a: "der", e: "Ich nehme im September Urlaub.", t: "vacation / holiday", c: "Reisen" },
  { w: "Straße", a: "die", e: "In welcher Straße wohnen Sie?", t: "street", c: "Reisen" },

  // Arbeit
  { w: "Arbeit", a: "die", e: "Mein Bruder sucht Arbeit.", t: "work / job", c: "Arbeit" },
  { w: "arbeiten", a: "", e: "Wo arbeiten Sie?", t: "to work", c: "Arbeit" },
  { w: "Beruf", a: "der", e: "Was ist Ihr Beruf?", t: "profession / occupation", c: "Arbeit" },
  { w: "Job", a: "der", e: "Jenny hat einen neuen Job.", t: "job", c: "Arbeit" },
  { w: "Firma", a: "die", e: "Er arbeitet bei einer Firma.", t: "company / firm", c: "Arbeit" },
  { w: "Chef", a: "der", e: "Wir haben eine neue Chefin.", t: "boss", c: "Arbeit" },
  { w: "Kollege", a: "der", e: "Wie heißt die neue Kollegin?", t: "colleague", c: "Arbeit" },
  { w: "Lehrer", a: "der", e: "Unsere Lehrerin heißt Frau Müller.", t: "teacher", c: "Arbeit" },
  { w: "Arzt", a: "der", e: "Ich habe einen Termin beim Arzt.", t: "doctor", c: "Arbeit" },
  { w: "Student", a: "der", e: "Ich bin Studentin.", t: "student", c: "Arbeit" },
  { w: "Termin", a: "der", e: "Machen wir sofort einen Termin.", t: "appointment", c: "Arbeit" },

  // Lernen
  { w: "Schule", a: "die", e: "Meine Tochter geht in die Schule.", t: "school", c: "Lernen" },
  { w: "Kurs", a: "der", e: "Der Deutschkurs geht bis zum Sommer.", t: "course", c: "Lernen" },
  { w: "Unterricht", a: "der", e: "Unterricht von 8 bis 12 Uhr.", t: "class / lesson", c: "Lernen" },
  { w: "Prüfung", a: "die", e: "Die Prüfung ist am Montag.", t: "exam", c: "Lernen" },
  { w: "Test", a: "der", e: "Der Test war einfach.", t: "test", c: "Lernen" },
  { w: "lernen", a: "", e: "Wie lange lernen Sie schon Deutsch?", t: "to learn", c: "Lernen" },
  { w: "Sprache", a: "die", e: "Welche Sprachen sprichst du?", t: "language", c: "Lernen" },

  // Verben
  { w: "gehen", a: "", e: "Ich muss zum Arzt gehen.", t: "to go", c: "Verben" },
  { w: "kommen", a: "", e: "Woher kommen Sie?", t: "to come", c: "Verben" },
  { w: "fahren", a: "", e: "Ich fahre mit dem Auto zur Arbeit.", t: "to drive / travel", c: "Verben" },
  { w: "machen", a: "", e: "Was machst du heute Abend?", t: "to do / make", c: "Verben" },
  { w: "sprechen", a: "", e: "Kann ich mit Herrn Klein sprechen?", t: "to speak", c: "Verben" },
  { w: "schreiben", a: "", e: "Er schreibt jeden Tag E-Mails.", t: "to write", c: "Verben" },
  { w: "lesen", a: "", e: "Ich lese ein Buch.", t: "to read", c: "Verben" },
  { w: "hören", a: "", e: "Hör mal! Was ist das?", t: "to hear / listen", c: "Verben" },
  { w: "sehen", a: "", e: "Ich kann dich nicht sehen.", t: "to see", c: "Verben" },
  { w: "essen", a: "", e: "Was gibt es zu essen?", t: "to eat", c: "Verben" },
  { w: "trinken", a: "", e: "Möchtest du etwas trinken?", t: "to drink", c: "Verben" },
  { w: "schlafen", a: "", e: "Ich schlafe acht Stunden.", t: "to sleep", c: "Verben" },
  { w: "wohnen", a: "", e: "Ich wohne in München.", t: "to live", c: "Verben" },
  { w: "helfen", a: "", e: "Können Sie mir helfen?", t: "to help", c: "Verben" },
  { w: "brauchen", a: "", e: "Brauchst du die Zeitung noch?", t: "to need", c: "Verben" },
  { w: "möchten", a: "", e: "Was möchten Sie trinken?", t: "would like", c: "Verben" },
  { w: "können", a: "", e: "Ich kann Deutsch und Russisch.", t: "can / to be able to", c: "Verben" },
  { w: "müssen", a: "", e: "Ich muss von 8 bis 18 Uhr arbeiten.", t: "must / to have to", c: "Verben" },
  { w: "sollen", a: "", e: "Was soll ich mitbringen?", t: "should / to be supposed to", c: "Verben" },
  { w: "dürfen", a: "", e: "Sie dürfen hier nicht rauchen.", t: "may / to be allowed to", c: "Verben" },
  { w: "wollen", a: "", e: "Wollen Sie einen Kaffee?", t: "to want", c: "Verben" },
  { w: "kennen", a: "", e: "Kennen Sie diese Frau?", t: "to know (a person)", c: "Verben" },
  { w: "wissen", a: "", e: "Weißt du, wie er heißt?", t: "to know (a fact)", c: "Verben" },
  { w: "nehmen", a: "", e: "Ich nehme den Bus.", t: "to take", c: "Verben" },
  { w: "geben", a: "", e: "Geben Sie mir bitte den Kugelschreiber.", t: "to give", c: "Verben" },
  { w: "stehen", a: "", e: "Der Bus steht an der Haltestelle.", t: "to stand", c: "Verben" },
  { w: "kochen", a: "", e: "Herr Georgi kann gut kochen.", t: "to cook", c: "Verben" },
  { w: "spielen", a: "", e: "Die Kinder spielen draußen.", t: "to play", c: "Verben" },
  { w: "schwimmen", a: "", e: "Ich schwimme jeden Tag.", t: "to swim", c: "Verben" },
  { w: "beginnen", a: "", e: "Das Spiel beginnt um 15.30 Uhr.", t: "to begin / start", c: "Verben" },
  { w: "aufstehen", a: "", e: "Ich muss um vier Uhr aufstehen.", t: "to get up", c: "Verben" },
  { w: "anrufen", a: "", e: "Kann man Sie anrufen?", t: "to call", c: "Verben" },
  { w: "einkaufen", a: "", e: "Ich muss noch einkaufen.", t: "to go shopping", c: "Verben" },
  { w: "verstehen", a: "", e: "Können Sie mich verstehen?", t: "to understand", c: "Verben" },

  // Adjektive
  { w: "gut", a: "", e: "Das finde ich gut.", t: "good", c: "Adjektive" },
  { w: "schlecht", a: "", e: "Mir ist schlecht!", t: "bad", c: "Adjektive" },
  { w: "schön", a: "", e: "Das ist sehr schön.", t: "beautiful / nice", c: "Adjektive" },
  { w: "groß", a: "", e: "Frankfurt ist eine große Stadt.", t: "big / tall", c: "Adjektive" },
  { w: "klein", a: "", e: "Eltville ist eine kleine Stadt.", t: "small / little", c: "Adjektive" },
  { w: "alt", a: "", e: "Wie alt sind Sie?", t: "old", c: "Adjektive" },
  { w: "neu", a: "", e: "Ich bin der neue Kollege.", t: "new", c: "Adjektive" },
  { w: "jung", a: "", e: "Noch so jung?", t: "young", c: "Adjektive" },
  { w: "schnell", a: "", e: "Er fährt schnell.", t: "fast / quick", c: "Adjektive" },
  { w: "langsam", a: "", e: "Bitte etwas langsamer sprechen.", t: "slow", c: "Adjektive" },
  { w: "leicht", a: "", e: "Der Koffer ist leicht.", t: "light / easy", c: "Adjektive" },
  { w: "schwer", a: "", e: "Ist Ihr Gepäck sehr schwer?", t: "heavy / difficult", c: "Adjektive" },
  { w: "krank", a: "", e: "Ich bin krank.", t: "sick / ill", c: "Adjektive" },
  { w: "müde", a: "", e: "Ich bin müde.", t: "tired", c: "Adjektive" },
  { w: "frei", a: "", e: "Ist der Platz noch frei?", t: "free / available", c: "Adjektive" },
  { w: "richtig", a: "", e: "Das ist richtig.", t: "right / correct", c: "Adjektive" },
  { w: "falsch", a: "", e: "Das ist falsch.", t: "wrong / false", c: "Adjektive" },
  { w: "einfach", a: "", e: "Die Prüfung ist ganz einfach.", t: "simple / easy", c: "Adjektive" },
  { w: "wichtig", a: "", e: "Dieses Formular ist sehr wichtig.", t: "important", c: "Adjektive" },
  { w: "kaputt", a: "", e: "Das Glas ist kaputt.", t: "broken", c: "Adjektive" },
  { w: "fertig", a: "", e: "Bist du fertig?", t: "ready / done", c: "Adjektive" },
  { w: "laut", a: "", e: "Nicht so laut! Das Baby schläft.", t: "loud / noisy", c: "Adjektive" },
  { w: "ruhig", a: "", e: "Ich möchte ein ruhiges Zimmer.", t: "quiet / calm", c: "Adjektive" },

  // Kommunikation
  { w: "Hallo", a: "", e: "Hallo! Wie geht's?", t: "hello", c: "Kommunikation" },
  { w: "Guten Morgen", a: "", e: "Guten Morgen!", t: "good morning", c: "Kommunikation" },
  { w: "Guten Tag", a: "", e: "Guten Tag, Herr Sommer!", t: "good day / hello", c: "Kommunikation" },
  { w: "Auf Wiedersehen", a: "", e: "Auf Wiedersehen!", t: "goodbye", c: "Kommunikation" },
  { w: "Tschüss", a: "", e: "Tschüss! Bis morgen!", t: "bye", c: "Kommunikation" },
  { w: "Danke", a: "", e: "Vielen Dank!", t: "thank you", c: "Kommunikation" },
  { w: "Bitte", a: "", e: "Eine Tasse Kaffee, bitte!", t: "please / you're welcome", c: "Kommunikation" },
  { w: "Entschuldigung", a: "die", e: "Entschuldigung! – Bitte.", t: "excuse me / sorry", c: "Kommunikation" },
  { w: "ja", a: "", e: "Ja.", t: "yes", c: "Kommunikation" },
  { w: "nein", a: "", e: "Nein, ich habe keine Zeit.", t: "no", c: "Kommunikation" },
  { w: "Hilfe", a: "die", e: "Hilfe! Bitte helfen Sie mir!", t: "help", c: "Kommunikation" },

  // Orte
  { w: "Stadt", a: "die", e: "Heidelberg ist eine alte Stadt.", t: "city / town", c: "Orte" },
  { w: "Post", a: "die", e: "Wo ist die Post, bitte?", t: "post office", c: "Orte" },
  { w: "Bank", a: "die", e: "Die Bank schließt um vier Uhr.", t: "bank", c: "Orte" },
  { w: "Polizei", a: "die", e: "Holen Sie die Polizei!", t: "police", c: "Orte" },
  { w: "Kino", a: "das", e: "Wir sehen im Kino einen Film.", t: "cinema / movie theater", c: "Orte" },
  { w: "Bäckerei", a: "die", e: "Ich geh zur Bäckerei.", t: "bakery", c: "Orte" },
  { w: "Kindergarten", a: "der", e: "Laura geht in den Kindergarten.", t: "kindergarten / preschool", c: "Orte" },
  { w: "Schwimmbad", a: "das", e: "Kommst du mit ins Schwimmbad?", t: "swimming pool", c: "Orte" },

  // Gesundheit
  { w: "Kopf", a: "der", e: "Mein Kopf tut weh!", t: "head", c: "Gesundheit" },
  { w: "Auge", a: "das", e: "Er hat blaue Augen.", t: "eye", c: "Gesundheit" },
  { w: "Hand", a: "die", e: "Er gibt mir die Hand.", t: "hand", c: "Gesundheit" },
  { w: "Arm", a: "der", e: "Mein Arm tut weh.", t: "arm", c: "Gesundheit" },
  { w: "Bein", a: "das", e: "Mein rechtes Bein tut weh.", t: "leg", c: "Gesundheit" },
  { w: "Fuß", a: "der", e: "Der linke Fuß tut mir weh.", t: "foot", c: "Gesundheit" },
  { w: "Bauch", a: "der", e: "Mein Bauch tut weh.", t: "stomach / belly", c: "Gesundheit" },
  { w: "Hunger", a: "der", e: "Ich habe Hunger!", t: "hunger", c: "Gesundheit" },
  { w: "Durst", a: "der", e: "Ich habe großen Durst.", t: "thirst", c: "Gesundheit" },
  { w: "Doktor", a: "der", e: "Wir gehen zum Doktor.", t: "doctor", c: "Gesundheit" },

  // Technik
  { w: "Telefon", a: "das", e: "Haben Sie Telefon?", t: "telephone", c: "Technik" },
  { w: "Handy", a: "das", e: "Bitte die Handys ausmachen!", t: "mobile phone", c: "Technik" },
  { w: "Computer", a: "der", e: "Wann bekommst du deinen Computer?", t: "computer", c: "Technik" },
  { w: "Internet", a: "das", e: "Das findest du im Internet.", t: "internet", c: "Technik" },
  { w: "E-Mail", a: "die", e: "Ich habe Ihre E-Mail nicht bekommen.", t: "email", c: "Technik" },
  { w: "Brief", a: "der", e: "Haben Sie einen Brief für mich?", t: "letter", c: "Technik" },
  { w: "Zeitung", a: "die", e: "Ich lese gern Zeitung.", t: "newspaper", c: "Technik" },
  { w: "Foto", a: "das", e: "Darf ich ein Foto machen?", t: "photo", c: "Technik" },
  { w: "Buch", a: "das", e: "Gute Bücher sind oft teuer.", t: "book", c: "Technik" },

  // Kleidung
  { w: "Kleidung", a: "die", e: "Wo finde ich Kleidung?", t: "clothing / clothes", c: "Kleidung" },
  { w: "Jacke", a: "die", e: "Zieh dir eine Jacke an!", t: "jacket", c: "Kleidung" },
  { w: "Schuh", a: "der", e: "Zieh die Schuhe aus!", t: "shoe", c: "Kleidung" },

  // Wetter
  { w: "Wetter", a: "das", e: "Wir hatten schlechtes Wetter.", t: "weather", c: "Wetter" },
  { w: "Regen", a: "der", e: "Bei diesem Regen gehe ich nicht raus.", t: "rain", c: "Wetter" },
  { w: "Sonne", a: "die", e: "Die Sonne scheint.", t: "sun", c: "Wetter" },
  { w: "kalt", a: "", e: "Mir ist kalt.", t: "cold", c: "Wetter" },
  { w: "warm", a: "", e: "Es ist warm heute.", t: "warm", c: "Wetter" },

  // Sonstiges
  { w: "aber", a: "", e: "Ich bin oft im Büro, aber nur kurz.", t: "but", c: "Sonstiges" },
  { w: "auch", a: "", e: "Ich bin auch Spanier.", t: "also / too", c: "Sonstiges" },
  { w: "dann", a: "", e: "Erst zur Post, dann komme ich.", t: "then", c: "Sonstiges" },
  { w: "gern(e)", a: "", e: "Ich gehe gerne einkaufen.", t: "gladly / with pleasure", c: "Sonstiges" },
  { w: "heute", a: "", e: "Heute ist ein schöner Tag.", t: "today", c: "Sonstiges" },
  { w: "hier", a: "", e: "Hier wohne ich.", t: "here", c: "Sonstiges" },
  { w: "immer", a: "", e: "Sie kommt immer zu spät.", t: "always", c: "Sonstiges" },
  { w: "jetzt", a: "", e: "Jetzt machen wir Pause.", t: "now", c: "Sonstiges" },
  { w: "morgen", a: "", e: "Morgen beginnt die Schule.", t: "tomorrow", c: "Sonstiges" },
  { w: "gestern", a: "", e: "Gestern war ich krank.", t: "yesterday", c: "Sonstiges" },
  { w: "nicht", a: "", e: "Das stimmt nicht.", t: "not", c: "Sonstiges" },
  { w: "noch", a: "", e: "Wir warten noch fünf Minuten.", t: "still / yet", c: "Sonstiges" },
  { w: "nur", a: "", e: "Ich möchte nur ein Glas Wasser.", t: "only / just", c: "Sonstiges" },
  { w: "sehr", a: "", e: "Danke sehr!", t: "very", c: "Sonstiges" },
  { w: "viel", a: "", e: "Hier regnet es viel.", t: "much / many", c: "Sonstiges" },
  { w: "zusammen", a: "", e: "Sollen wir zusammen essen gehen?", t: "together", c: "Sonstiges" },
  { w: "rechts", a: "", e: "Die Straße ist hier rechts.", t: "right", c: "Sonstiges" },
  { w: "links", a: "", e: "Gehen Sie die nächste Straße links.", t: "left", c: "Sonstiges" },
  { w: "geradeaus", a: "", e: "Gehen Sie immer geradeaus!", t: "straight ahead", c: "Sonstiges" },
  { w: "Deutschland", a: "", e: "Ich wohne in Deutschland.", t: "Germany", c: "Sonstiges" },
  { w: "Formular", a: "das", e: "Füllen Sie dieses Formular aus.", t: "form", c: "Sonstiges" },
  { w: "Ausweis", a: "der", e: "Hier ist mein Ausweis.", t: "ID card", c: "Sonstiges" },
  { w: "Hobby", a: "das", e: "Meine Hobbys sind Wandern und Schwimmen.", t: "hobby", c: "Sonstiges" },
  { w: "Sport", a: "der", e: "Ich mache viel Sport.", t: "sport", c: "Sonstiges" },
  { w: "Fußball", a: "der", e: "Spielt ihr gerne Fußball?", t: "football / soccer", c: "Sonstiges" },
  { w: "Geschenk", a: "das", e: "Danke für das schöne Geschenk.", t: "gift / present", c: "Sonstiges" },
  { w: "Einladung", a: "die", e: "Danke für die Einladung!", t: "invitation", c: "Sonstiges" },

  // Zahlen — missing numbers
  { w: "null", a: "", e: "Es gibt null Probleme.", t: "zero", c: "Zahlen" },
  { w: "elf", a: "", e: "Um elf Uhr bin ich da.", t: "eleven", c: "Zahlen" },
  { w: "zwölf", a: "", e: "Zwölf Monate hat ein Jahr.", t: "twelve", c: "Zahlen" },
  { w: "dreizehn", a: "", e: "Er ist dreizehn Jahre alt.", t: "thirteen", c: "Zahlen" },
  { w: "vierzehn", a: "", e: "Der Zug fährt in vierzehn Minuten.", t: "fourteen", c: "Zahlen" },
  { w: "fünfzehn", a: "", e: "Um fünfzehn Uhr.", t: "fifteen", c: "Zahlen" },
  { w: "sechzehn", a: "", e: "Das kostet sechzehn Euro.", t: "sixteen", c: "Zahlen" },
  { w: "siebzehn", a: "", e: "Um siebzehn Uhr beginnt der Film.", t: "seventeen", c: "Zahlen" },
  { w: "achtzehn", a: "", e: "Mit achtzehn Jahren ist man erwachsen.", t: "eighteen", c: "Zahlen" },
  { w: "neunzehn", a: "", e: "Der Bus Nummer neunzehn.", t: "nineteen", c: "Zahlen" },
  { w: "dreißig", a: "", e: "Ich bin dreißig Jahre alt.", t: "thirty", c: "Zahlen" },
  { w: "vierzig", a: "", e: "Das kostet vierzig Euro.", t: "forty", c: "Zahlen" },
  { w: "fünfzig", a: "", e: "Fünfzig Prozent Rabatt!", t: "fifty", c: "Zahlen" },
  { w: "sechzig", a: "", e: "Das Auto fährt sechzig km/h.", t: "sixty", c: "Zahlen" },
  { w: "siebzig", a: "", e: "Mein Großvater ist siebzig Jahre alt.", t: "seventy", c: "Zahlen" },
  { w: "achtzig", a: "", e: "Das Buch kostet achtzig Euro.", t: "eighty", c: "Zahlen" },
  { w: "neunzig", a: "", e: "Der Zug fährt neunzig Kilometer pro Stunde.", t: "ninety", c: "Zahlen" },

  // Jahreszeiten
  { w: "Frühling", a: "der", e: "Im Frühling ist es warm und schön.", t: "spring", c: "Jahreszeiten" },
  { w: "Sommer", a: "der", e: "Im Sommer fahren wir ans Meer.", t: "summer", c: "Jahreszeiten" },
  { w: "Herbst", a: "der", e: "Im Herbst fallen die Blätter.", t: "autumn / fall", c: "Jahreszeiten" },
  { w: "Winter", a: "der", e: "Im Winter liegt Schnee.", t: "winter", c: "Jahreszeiten" },

  // Zeit — weitere Wörter
  { w: "Datum", a: "das", e: "Was ist heute das Datum?", t: "date", c: "Zeit" },
  { w: "Monat", a: "der", e: "Wie viele Tage hat dieser Monat?", t: "month", c: "Zeit" },
  { w: "Kalender", a: "der", e: "Ich schaue in den Kalender.", t: "calendar", c: "Zeit" },
  { w: "früh", a: "", e: "Ich stehe früh auf.", t: "early", c: "Zeit" },
  { w: "spät", a: "", e: "Es ist schon sehr spät.", t: "late", c: "Zeit" },
  { w: "bald", a: "", e: "Ich bin bald zurück.", t: "soon", c: "Zeit" },
  { w: "zuerst", a: "", e: "Zuerst lerne ich, dann schlafe ich.", t: "first / firstly", c: "Zeit" },
  { w: "danach", a: "", e: "Wir essen, und danach gehen wir spazieren.", t: "afterwards", c: "Zeit" },
  { w: "meistens", a: "", e: "Meistens stehe ich um sieben Uhr auf.", t: "mostly / usually", c: "Zeit" },

  // Person — weitere Wörter
  { w: "Großeltern", a: "die", e: "Meine Großeltern wohnen in Bayern.", t: "grandparents", c: "Person" },
  { w: "Onkel", a: "der", e: "Mein Onkel heißt Klaus.", t: "uncle", c: "Person" },
  { w: "Tante", a: "die", e: "Meine Tante bringt mir immer Geschenke.", t: "aunt", c: "Person" },
  { w: "Ehemann", a: "der", e: "Ihr Ehemann arbeitet als Arzt.", t: "husband", c: "Person" },
  { w: "Ehefrau", a: "die", e: "Sein Ehefrau kommt aus Italien.", t: "wife", c: "Person" },
  { w: "Nachbar", a: "der", e: "Mein Nachbar ist sehr nett.", t: "neighbour", c: "Person" },
  { w: "Herr", a: "der", e: "Herr Müller, bitte kommen Sie herein.", t: "Mr. / gentleman", c: "Person" },
  { w: "Baby", a: "das", e: "Das Baby schläft gerade.", t: "baby", c: "Person" },
  { w: "Junge", a: "der", e: "Der Junge spielt Fußball.", t: "boy", c: "Person" },
  { w: "Mädchen", a: "das", e: "Das Mädchen liest ein Buch.", t: "girl", c: "Person" },

  // Wohnen — weitere Wörter
  { w: "Badezimmer", a: "das", e: "Das Badezimmer ist im ersten Stock.", t: "bathroom", c: "Wohnen" },
  { w: "Dusche", a: "die", e: "Ich nehme jeden Morgen eine Dusche.", t: "shower", c: "Wohnen" },
  { w: "Eingang", a: "der", e: "Der Eingang ist auf der linken Seite.", t: "entrance", c: "Wohnen" },
  { w: "Erdgeschoss", a: "das", e: "Wir wohnen im Erdgeschoss.", t: "ground floor", c: "Wohnen" },
  { w: "Fenster", a: "das", e: "Bitte mach das Fenster auf!", t: "window", c: "Wohnen" },
  { w: "Flur", a: "der", e: "Die Jacken hängen im Flur.", t: "hallway", c: "Wohnen" },
  { w: "Garage", a: "die", e: "Das Auto steht in der Garage.", t: "garage", c: "Wohnen" },
  { w: "Heizung", a: "die", e: "Die Heizung ist kaputt.", t: "heating", c: "Wohnen" },
  { w: "Keller", a: "der", e: "Im Keller lagern wir Fahrräder.", t: "basement / cellar", c: "Wohnen" },
  { w: "Lampe", a: "die", e: "Die Lampe gibt gutes Licht.", t: "lamp / light", c: "Wohnen" },
  { w: "Regal", a: "das", e: "Die Bücher stehen im Regal.", t: "shelf", c: "Wohnen" },
  { w: "Schlafzimmer", a: "das", e: "Das Schlafzimmer ist rechts.", t: "bedroom", c: "Wohnen" },
  { w: "Sofa", a: "das", e: "Ich sitze auf dem Sofa.", t: "sofa / couch", c: "Wohnen" },
  { w: "Steckdose", a: "die", e: "Wo ist die Steckdose?", t: "power socket", c: "Wohnen" },
  { w: "Stuhl", a: "der", e: "Bitte nimm einen Stuhl!", t: "chair", c: "Wohnen" },
  { w: "Toilette", a: "die", e: "Wo ist die Toilette, bitte?", t: "toilet", c: "Wohnen" },
  { w: "Tür", a: "die", e: "Bitte schließe die Tür!", t: "door", c: "Wohnen" },
  { w: "Vorhang", a: "der", e: "Bitte zieh den Vorhang zu.", t: "curtain", c: "Wohnen" },
  { w: "Waschmaschine", a: "die", e: "Die Waschmaschine läuft.", t: "washing machine", c: "Wohnen" },
  { w: "Wohnzimmer", a: "das", e: "Wir sehen im Wohnzimmer fern.", t: "living room", c: "Wohnen" },

  // Essen — weitere Wörter
  { w: "Abendessen", a: "das", e: "Was gibt es zum Abendessen?", t: "dinner / supper", c: "Essen" },
  { w: "Mittagessen", a: "das", e: "Wir essen um zwölf Uhr Mittagessen.", t: "lunch", c: "Essen" },
  { w: "Eis", a: "das", e: "Im Sommer esse ich gern Eis.", t: "ice cream", c: "Essen" },
  { w: "Flasche", a: "die", e: "Eine Flasche Wasser, bitte.", t: "bottle", c: "Essen" },
  { w: "Gabel", a: "die", e: "Ich brauche eine Gabel.", t: "fork", c: "Essen" },
  { w: "Glas", a: "das", e: "Ein Glas Saft, bitte.", t: "glass", c: "Essen" },
  { w: "Joghurt", a: "der", e: "Zum Frühstück esse ich Joghurt.", t: "yoghurt", c: "Essen" },
  { w: "Käse", a: "der", e: "Ich mag Käse auf dem Brot.", t: "cheese", c: "Essen" },
  { w: "Löffel", a: "der", e: "Ich esse die Suppe mit einem Löffel.", t: "spoon", c: "Essen" },
  { w: "Marmelade", a: "die", e: "Ich esse Brot mit Marmelade.", t: "jam", c: "Essen" },
  { w: "Messer", a: "das", e: "Bitte gib mir ein Messer.", t: "knife", c: "Essen" },
  { w: "Mineralwasser", a: "das", e: "Ein Mineralwasser, bitte.", t: "mineral water", c: "Essen" },
  { w: "Nudeln", a: "die", e: "Nudeln mit Tomatensoße sind lecker.", t: "pasta / noodles", c: "Essen" },
  { w: "Orange", a: "die", e: "Eine Orange zum Frühstück.", t: "orange", c: "Essen" },
  { w: "Schokolade", a: "die", e: "Ich mag Schokolade sehr.", t: "chocolate", c: "Essen" },
  { w: "Suppe", a: "die", e: "Die Suppe ist heiß.", t: "soup", c: "Essen" },
  { w: "Tasse", a: "die", e: "Eine Tasse Kaffee, bitte.", t: "cup", c: "Essen" },
  { w: "Teller", a: "der", e: "Der Teller ist leer.", t: "plate", c: "Essen" },
  { w: "Wurst", a: "die", e: "Ich möchte Wurst und Brot.", t: "sausage / cold cuts", c: "Essen" },
  { w: "Zucker", a: "der", e: "Möchten Sie Zucker im Kaffee?", t: "sugar", c: "Essen" },

  // Einkaufen — weitere Wörter
  { w: "Angebot", a: "das", e: "Das ist ein gutes Angebot.", t: "offer / special deal", c: "Einkaufen" },
  { w: "Cent", a: "der", e: "Das kostet fünfzig Cent.", t: "cent", c: "Einkaufen" },
  { w: "Euro", a: "der", e: "Das kostet zehn Euro.", t: "euro", c: "Einkaufen" },
  { w: "Größe", a: "die", e: "Welche Größe haben Sie?", t: "size", c: "Einkaufen" },
  { w: "Markt", a: "der", e: "Samstags gehe ich auf den Markt.", t: "market", c: "Einkaufen" },
  { w: "Quittung", a: "die", e: "Kann ich eine Quittung haben?", t: "receipt", c: "Einkaufen" },
  { w: "Supermarkt", a: "der", e: "Ich kaufe im Supermarkt ein.", t: "supermarket", c: "Einkaufen" },
  { w: "Tasche", a: "die", e: "Ich brauche eine Tasche.", t: "bag", c: "Einkaufen" },
  { w: "Einkaufsliste", a: "die", e: "Ich habe eine Einkaufsliste.", t: "shopping list", c: "Einkaufen" },

  // Reisen — weitere Wörter
  { w: "Abfahrt", a: "die", e: "Die Abfahrt ist um neun Uhr.", t: "departure", c: "Reisen" },
  { w: "Ankunft", a: "die", e: "Die Ankunft ist um elf Uhr.", t: "arrival", c: "Reisen" },
  { w: "Ausland", a: "das", e: "Im Ausland spreche ich Englisch.", t: "abroad / foreign country", c: "Reisen" },
  { w: "Autobahn", a: "die", e: "Wir fahren auf der Autobahn.", t: "motorway / highway", c: "Reisen" },
  { w: "Fahrt", a: "die", e: "Die Fahrt dauert zwei Stunden.", t: "journey / trip", c: "Reisen" },
  { w: "Gleis", a: "das", e: "Der Zug kommt auf Gleis fünf.", t: "platform / track", c: "Reisen" },
  { w: "Hafen", a: "der", e: "Das Schiff ist im Hafen.", t: "port / harbour", c: "Reisen" },
  { w: "Innenstadt", a: "die", e: "Das Hotel ist in der Innenstadt.", t: "city centre", c: "Reisen" },
  { w: "Norden", a: "der", e: "Wir fahren nach Norden.", t: "north", c: "Reisen" },
  { w: "Osten", a: "der", e: "Berlin liegt im Osten Deutschlands.", t: "east", c: "Reisen" },
  { w: "Parkplatz", a: "der", e: "Gibt es einen Parkplatz?", t: "car park / parking space", c: "Reisen" },
  { w: "Pass", a: "der", e: "Bitte zeigen Sie Ihren Pass.", t: "passport", c: "Reisen" },
  { w: "Reservierung", a: "die", e: "Ich habe eine Reservierung.", t: "reservation / booking", c: "Reisen" },
  { w: "Richtung", a: "die", e: "In welche Richtung ist der Bahnhof?", t: "direction", c: "Reisen" },
  { w: "Straßenbahn", a: "die", e: "Ich fahre mit der Straßenbahn.", t: "tram", c: "Reisen" },
  { w: "Süden", a: "der", e: "Im Süden ist es wärmer.", t: "south", c: "Reisen" },
  { w: "U-Bahn", a: "die", e: "Wir nehmen die U-Bahn.", t: "underground / subway", c: "Reisen" },
  { w: "Westen", a: "der", e: "Die Sonne geht im Westen unter.", t: "west", c: "Reisen" },

  // Arbeit — weitere Wörter
  { w: "Ausbildung", a: "die", e: "Ich mache eine Ausbildung als Koch.", t: "vocational training", c: "Arbeit" },
  { w: "Bewerbung", a: "die", e: "Ich schreibe eine Bewerbung.", t: "job application", c: "Arbeit" },
  { w: "Büro", a: "das", e: "Ich arbeite im Büro.", t: "office", c: "Arbeit" },
  { w: "Gehalt", a: "das", e: "Das Gehalt ist gut.", t: "salary", c: "Arbeit" },
  { w: "Kantine", a: "die", e: "Wir essen in der Kantine.", t: "canteen / cafeteria", c: "Arbeit" },
  { w: "Mitarbeiter", a: "der", e: "Die Mitarbeiter sind sehr nett.", t: "employee / colleague", c: "Arbeit" },
  { w: "Pause", a: "die", e: "Um zwölf Uhr machen wir Pause.", t: "break", c: "Arbeit" },
  { w: "Stelle", a: "die", e: "Ich suche eine neue Stelle.", t: "position / job", c: "Arbeit" },

  // Berufe
  { w: "Ärztin", a: "die", e: "Die Ärztin untersucht den Patienten.", t: "(female) doctor", c: "Berufe" },
  { w: "Busfahrer", a: "der", e: "Der Busfahrer kennt alle Haltestellen.", t: "bus driver", c: "Berufe" },
  { w: "Ingenieur", a: "der", e: "Er ist Ingenieur von Beruf.", t: "engineer", c: "Berufe" },
  { w: "Kellner", a: "der", e: "Der Kellner bringt die Speisekarte.", t: "waiter", c: "Berufe" },
  { w: "Koch", a: "der", e: "Der Koch kocht sehr gut.", t: "cook / chef", c: "Berufe" },
  { w: "Krankenschwester", a: "die", e: "Die Krankenschwester hilft den Patienten.", t: "nurse", c: "Berufe" },
  { w: "Mechaniker", a: "der", e: "Der Mechaniker repariert das Auto.", t: "mechanic", c: "Berufe" },
  { w: "Polizist", a: "der", e: "Der Polizist hilft uns.", t: "police officer", c: "Berufe" },
  { w: "Sekretärin", a: "die", e: "Die Sekretärin macht einen Termin.", t: "secretary", c: "Berufe" },
  { w: "Verkäufer", a: "der", e: "Der Verkäufer zeigt uns die Produkte.", t: "salesperson", c: "Berufe" },

  // Lernen — weitere Wörter
  { w: "Hausaufgaben", a: "die", e: "Ich mache meine Hausaufgaben.", t: "homework", c: "Lernen" },
  { w: "Klasse", a: "die", e: "Ich bin in der Klasse B1.", t: "class / classroom", c: "Lernen" },
  { w: "Note", a: "die", e: "Ich habe eine gute Note.", t: "grade / mark", c: "Lernen" },
  { w: "Stift", a: "der", e: "Hast du einen Stift?", t: "pen / pencil", c: "Lernen" },
  { w: "Stundenplan", a: "der", e: "Ich schaue auf den Stundenplan.", t: "timetable", c: "Lernen" },
  { w: "Tafel", a: "die", e: "Der Lehrer schreibt an die Tafel.", t: "blackboard / whiteboard", c: "Lernen" },
  { w: "Wörterbuch", a: "das", e: "Ich schlage das Wort im Wörterbuch nach.", t: "dictionary", c: "Lernen" },

  // Gesundheit — weitere Wörter
  { w: "Erkältung", a: "die", e: "Ich habe eine Erkältung.", t: "cold (illness)", c: "Gesundheit" },
  { w: "Fieber", a: "das", e: "Ich habe hohes Fieber.", t: "fever", c: "Gesundheit" },
  { w: "Krankenhaus", a: "das", e: "Er liegt im Krankenhaus.", t: "hospital", c: "Gesundheit" },
  { w: "Krankenkasse", a: "die", e: "Welche Krankenkasse haben Sie?", t: "health insurance", c: "Gesundheit" },
  { w: "Knie", a: "das", e: "Mein Knie tut weh.", t: "knee", c: "Gesundheit" },
  { w: "Medikament", a: "das", e: "Ich nehme das Medikament dreimal täglich.", t: "medicine / medication", c: "Gesundheit" },
  { w: "Mund", a: "der", e: "Bitte öffnen Sie den Mund.", t: "mouth", c: "Gesundheit" },
  { w: "Nase", a: "die", e: "Meine Nase läuft.", t: "nose", c: "Gesundheit" },
  { w: "Ohr", a: "das", e: "Mein Ohr tut weh.", t: "ear", c: "Gesundheit" },
  { w: "Rücken", a: "der", e: "Ich habe Rückenschmerzen.", t: "back", c: "Gesundheit" },
  { w: "Schmerzen", a: "die", e: "Ich habe starke Schmerzen.", t: "pain", c: "Gesundheit" },
  { w: "Schulter", a: "die", e: "Meine Schulter schmerzt.", t: "shoulder", c: "Gesundheit" },
  { w: "Tablette", a: "die", e: "Ich nehme eine Tablette.", t: "tablet / pill", c: "Gesundheit" },
  { w: "Zahn", a: "der", e: "Mein Zahn tut weh.", t: "tooth", c: "Gesundheit" },
  { w: "Zahnarzt", a: "der", e: "Ich gehe zum Zahnarzt.", t: "dentist", c: "Gesundheit" },

  // Körper
  { w: "Finger", a: "der", e: "Ich habe mir den Finger verletzt.", t: "finger", c: "Körper" },
  { w: "Gesicht", a: "das", e: "Sie hat ein freundliches Gesicht.", t: "face", c: "Körper" },
  { w: "Haar", a: "das", e: "Mein Haar ist lang und braun.", t: "hair", c: "Körper" },
  { w: "Herz", a: "das", e: "Mein Herz schlägt schnell.", t: "heart", c: "Körper" },
  { w: "Körper", a: "der", e: "Sport ist gut für den Körper.", t: "body", c: "Körper" },
  { w: "Lippe", a: "die", e: "Die Lippe ist verletzt.", t: "lip", c: "Körper" },

  // Kleidung — weitere Wörter
  { w: "Bluse", a: "die", e: "Sie trägt eine weiße Bluse.", t: "blouse", c: "Kleidung" },
  { w: "Hemd", a: "das", e: "Er trägt ein blaues Hemd.", t: "shirt", c: "Kleidung" },
  { w: "Hose", a: "die", e: "Die Hose ist zu groß.", t: "trousers / pants", c: "Kleidung" },
  { w: "Jeans", a: "die", e: "Ich trage am liebsten Jeans.", t: "jeans", c: "Kleidung" },
  { w: "Kleid", a: "das", e: "Das Kleid ist sehr schön.", t: "dress", c: "Kleidung" },
  { w: "Mantel", a: "der", e: "Es ist kalt — ich brauche einen Mantel.", t: "coat", c: "Kleidung" },
  { w: "Mütze", a: "die", e: "Im Winter trage ich eine Mütze.", t: "hat / beanie", c: "Kleidung" },
  { w: "Pullover", a: "der", e: "Der Pullover ist warm.", t: "jumper / sweater", c: "Kleidung" },
  { w: "Rock", a: "der", e: "Sie trägt einen roten Rock.", t: "skirt", c: "Kleidung" },
  { w: "Schal", a: "der", e: "Ich trage einen Schal.", t: "scarf", c: "Kleidung" },
  { w: "Socken", a: "die", e: "Ich suche meine Socken.", t: "socks", c: "Kleidung" },
  { w: "Stiefel", a: "der", e: "Die Stiefel sind aus Leder.", t: "boots", c: "Kleidung" },
  { w: "T-Shirt", a: "das", e: "Im Sommer trage ich ein T-Shirt.", t: "T-shirt", c: "Kleidung" },

  // Wetter — weitere Wörter
  { w: "Gewitter", a: "das", e: "Es gibt heute ein Gewitter.", t: "thunderstorm", c: "Wetter" },
  { w: "Grad", a: "der", e: "Es sind dreißig Grad heute.", t: "degree (temperature)", c: "Wetter" },
  { w: "Nebel", a: "der", e: "Im Herbst gibt es oft Nebel.", t: "fog", c: "Wetter" },
  { w: "Schnee", a: "der", e: "Im Winter liegt Schnee.", t: "snow", c: "Wetter" },
  { w: "Sturm", a: "der", e: "Der Sturm war sehr stark.", t: "storm", c: "Wetter" },
  { w: "Temperatur", a: "die", e: "Die Temperatur ist heute niedrig.", t: "temperature", c: "Wetter" },
  { w: "Wind", a: "der", e: "Der Wind ist kalt.", t: "wind", c: "Wetter" },
  { w: "heiß", a: "", e: "Im Sommer ist es heiß.", t: "hot", c: "Wetter" },
  { w: "sonnig", a: "", e: "Heute ist es sonnig.", t: "sunny", c: "Wetter" },
  { w: "bewölkt", a: "", e: "Der Himmel ist bewölkt.", t: "cloudy", c: "Wetter" },
  { w: "windig", a: "", e: "Es ist sehr windig heute.", t: "windy", c: "Wetter" },

  // Natur
  { w: "Baum", a: "der", e: "Der Baum ist sehr alt.", t: "tree", c: "Natur" },
  { w: "Berg", a: "der", e: "Wir wandern auf den Berg.", t: "mountain", c: "Natur" },
  { w: "Blume", a: "die", e: "Die Blume ist schön.", t: "flower", c: "Natur" },
  { w: "Fluss", a: "der", e: "Der Fluss fließt durch die Stadt.", t: "river", c: "Natur" },
  { w: "Gras", a: "das", e: "Das Gras ist grün.", t: "grass", c: "Natur" },
  { w: "Hund", a: "der", e: "Mein Hund heißt Bello.", t: "dog", c: "Natur" },
  { w: "Katze", a: "die", e: "Die Katze schläft auf dem Sofa.", t: "cat", c: "Natur" },
  { w: "Luft", a: "die", e: "Die Luft hier ist frisch.", t: "air", c: "Natur" },
  { w: "Meer", a: "das", e: "Wir fahren ans Meer.", t: "sea", c: "Natur" },
  { w: "See", a: "der", e: "Am See ist es sehr schön.", t: "lake", c: "Natur" },
  { w: "Tier", a: "das", e: "Ein Tier im Zoo.", t: "animal", c: "Natur" },
  { w: "Vogel", a: "der", e: "Der Vogel singt schön.", t: "bird", c: "Natur" },
  { w: "Wald", a: "der", e: "Wir machen einen Spaziergang im Wald.", t: "forest / woods", c: "Natur" },
  { w: "Wiese", a: "die", e: "Die Kinder spielen auf der Wiese.", t: "meadow", c: "Natur" },

  // Orte — weitere Wörter
  { w: "Apotheke", a: "die", e: "Ich hole die Tabletten aus der Apotheke.", t: "pharmacy", c: "Orte" },
  { w: "Bibliothek", a: "die", e: "Ich leihe ein Buch in der Bibliothek.", t: "library", c: "Orte" },
  { w: "Bushaltestelle", a: "die", e: "Die Bushaltestelle ist um die Ecke.", t: "bus stop", c: "Orte" },
  { w: "Kirche", a: "die", e: "Die Kirche ist im Zentrum.", t: "church", c: "Orte" },
  { w: "Museum", a: "das", e: "Das Museum ist sehr interessant.", t: "museum", c: "Orte" },
  { w: "Park", a: "der", e: "Wir gehen in den Park.", t: "park", c: "Orte" },
  { w: "Rathaus", a: "das", e: "Das Rathaus ist im Stadtzentrum.", t: "town hall", c: "Orte" },
  { w: "Stadtzentrum", a: "das", e: "Das Hotel liegt im Stadtzentrum.", t: "city centre", c: "Orte" },
  { w: "Tankstelle", a: "die", e: "Wir halten an der Tankstelle.", t: "petrol station", c: "Orte" },
  { w: "Zoo", a: "der", e: "Am Wochenende gehen wir in den Zoo.", t: "zoo", c: "Orte" },

  // Kommunikation — weitere Wörter
  { w: "Anruf", a: "der", e: "Ich habe einen Anruf verpasst.", t: "phone call", c: "Kommunikation" },
  { w: "Anschrift", a: "die", e: "Bitte geben Sie Ihre Anschrift an.", t: "address (formal)", c: "Kommunikation" },
  { w: "App", a: "die", e: "Ich nutze eine App für Deutsch.", t: "app", c: "Kommunikation" },
  { w: "Nachricht", a: "die", e: "Ich habe eine Nachricht bekommen.", t: "message", c: "Kommunikation" },
  { w: "Nummer", a: "die", e: "Wie ist Ihre Nummer?", t: "number", c: "Kommunikation" },
  { w: "Postkarte", a: "die", e: "Ich schicke eine Postkarte aus dem Urlaub.", t: "postcard", c: "Kommunikation" },
  { w: "Website", a: "die", e: "Besuchen Sie unsere Website.", t: "website", c: "Kommunikation" },

  // Technik — weitere Wörter
  { w: "Drucker", a: "der", e: "Der Drucker ist kaputt.", t: "printer", c: "Technik" },
  { w: "Fernseher", a: "der", e: "Wir sehen abends fern.", t: "TV / television", c: "Technik" },
  { w: "Kamera", a: "die", e: "Ich mache Fotos mit der Kamera.", t: "camera", c: "Technik" },
  { w: "Mikrofon", a: "das", e: "Das Mikrofon funktioniert nicht.", t: "microphone", c: "Technik" },
  { w: "Radio", a: "das", e: "Ich höre Radio im Auto.", t: "radio", c: "Technik" },
  { w: "Tablet", a: "das", e: "Ich lese auf meinem Tablet.", t: "tablet", c: "Technik" },

  // Freizeit
  { w: "Ausflug", a: "der", e: "Wir machen einen Ausflug.", t: "trip / excursion", c: "Freizeit" },
  { w: "Film", a: "der", e: "Der Film war sehr gut.", t: "film / movie", c: "Freizeit" },
  { w: "Konzert", a: "das", e: "Wir gehen zu einem Konzert.", t: "concert", c: "Freizeit" },
  { w: "Musik", a: "die", e: "Ich höre gern Musik.", t: "music", c: "Freizeit" },
  { w: "Spaziergang", a: "der", e: "Wir machen einen Spaziergang im Park.", t: "walk / stroll", c: "Freizeit" },
  { w: "Theater", a: "das", e: "Am Samstag gehen wir ins Theater.", t: "theatre", c: "Freizeit" },
  { w: "Tennis", a: "das", e: "Ich spiele Tennis am Wochenende.", t: "tennis", c: "Freizeit" },
  { w: "Basketball", a: "der", e: "Basketball ist mein Lieblingssport.", t: "basketball", c: "Freizeit" },
  { w: "Volleyball", a: "der", e: "Wir spielen Volleyball am Strand.", t: "volleyball", c: "Freizeit" },
  { w: "Yoga", a: "das", e: "Ich mache jeden Morgen Yoga.", t: "yoga", c: "Freizeit" },
  { w: "Radfahren", a: "das", e: "Radfahren macht mir Spaß.", t: "cycling", c: "Freizeit" },
  { w: "Laufen", a: "das", e: "Laufen ist gut für die Gesundheit.", t: "running", c: "Freizeit" },
  { w: "Turnen", a: "das", e: "Die Kinder haben Turnen in der Schule.", t: "gymnastics", c: "Freizeit" },

  // Verben — weitere Wörter
  { w: "anmelden", a: "", e: "Ich möchte mich für den Kurs anmelden.", t: "to register / sign up", c: "Verben" },
  { w: "antworten", a: "", e: "Bitte antworten Sie auf die Frage.", t: "to answer / reply", c: "Verben" },
  { w: "aufräumen", a: "", e: "Ich räume heute mein Zimmer auf.", t: "to tidy up", c: "Verben" },
  { w: "besuchen", a: "", e: "Ich besuche meine Eltern am Wochenende.", t: "to visit", c: "Verben" },
  { w: "bestellen", a: "", e: "Ich möchte einen Kaffee bestellen.", t: "to order", c: "Verben" },
  { w: "buchstabieren", a: "", e: "Können Sie das buchstabieren?", t: "to spell", c: "Verben" },
  { w: "bügeln", a: "", e: "Ich muss die Hemden bügeln.", t: "to iron", c: "Verben" },
  { w: "einladen", a: "", e: "Ich lade meine Freunde ein.", t: "to invite", c: "Verben" },
  { w: "empfehlen", a: "", e: "Können Sie ein Restaurant empfehlen?", t: "to recommend", c: "Verben" },
  { w: "erklären", a: "", e: "Können Sie das erklären?", t: "to explain", c: "Verben" },
  { w: "finden", a: "", e: "Wo finde ich den Supermarkt?", t: "to find", c: "Verben" },
  { w: "fragen", a: "", e: "Ich möchte etwas fragen.", t: "to ask", c: "Verben" },
  { w: "kennenlernen", a: "", e: "Ich möchte Sie kennenlernen.", t: "to get to know", c: "Verben" },
  { w: "liegen", a: "", e: "Das Buch liegt auf dem Tisch.", t: "to lie / to be located", c: "Verben" },
  { w: "packen", a: "", e: "Ich packe meinen Koffer.", t: "to pack", c: "Verben" },
  { w: "planen", a: "", e: "Wir planen unseren Urlaub.", t: "to plan", c: "Verben" },
  { w: "probieren", a: "", e: "Möchten Sie probieren?", t: "to try / taste", c: "Verben" },
  { w: "putzen", a: "", e: "Ich putze heute das Bad.", t: "to clean", c: "Verben" },
  { w: "reisen", a: "", e: "Ich reise gern nach Europa.", t: "to travel", c: "Verben" },
  { w: "reparieren", a: "", e: "Können Sie das reparieren?", t: "to repair", c: "Verben" },
  { w: "schicken", a: "", e: "Ich schicke dir eine Nachricht.", t: "to send", c: "Verben" },
  { w: "suchen", a: "", e: "Ich suche die Toilette.", t: "to look for / search", c: "Verben" },
  { w: "tanzen", a: "", e: "Wir tanzen gern.", t: "to dance", c: "Verben" },
  { w: "treffen", a: "", e: "Wir treffen uns um drei Uhr.", t: "to meet", c: "Verben" },
  { w: "umsteigen", a: "", e: "Sie müssen in München umsteigen.", t: "to change (trains/buses)", c: "Verben" },
  { w: "warten", a: "", e: "Bitte warten Sie hier.", t: "to wait", c: "Verben" },
  { w: "wandern", a: "", e: "Wir wandern in den Bergen.", t: "to hike", c: "Verben" },
  { w: "waschen", a: "", e: "Ich wasche die Wäsche.", t: "to wash", c: "Verben" },
  { w: "zeigen", a: "", e: "Können Sie mir zeigen, wo das ist?", t: "to show", c: "Verben" },

  // Adjektive — weitere Wörter
  { w: "allein", a: "", e: "Ich bin heute allein zu Hause.", t: "alone", c: "Adjektive" },
  { w: "anders", a: "", e: "Das ist ganz anders als ich dachte.", t: "different", c: "Adjektive" },
  { w: "bekannt", a: "", e: "Das ist ein bekanntes Restaurant.", t: "well-known / familiar", c: "Adjektive" },
  { w: "bequem", a: "", e: "Das Sofa ist sehr bequem.", t: "comfortable", c: "Adjektive" },
  { w: "direkt", a: "", e: "Gibt es eine direkte Verbindung?", t: "direct", c: "Adjektive" },
  { w: "dunkel", a: "", e: "Es ist dunkel draußen.", t: "dark", c: "Adjektive" },
  { w: "eigen", a: "", e: "Ich habe ein eigenes Zimmer.", t: "own", c: "Adjektive" },
  { w: "freundlich", a: "", e: "Der Kellner ist sehr freundlich.", t: "friendly", c: "Adjektive" },
  { w: "frisch", a: "", e: "Das Brot ist frisch.", t: "fresh", c: "Adjektive" },
  { w: "gleich", a: "", e: "Das ist das gleiche Problem.", t: "same / equal", c: "Adjektive" },
  { w: "günstig", a: "", e: "Das ist sehr günstig!", t: "affordable / favourable", c: "Adjektive" },
  { w: "hell", a: "", e: "Das Zimmer ist hell und groß.", t: "bright / light", c: "Adjektive" },
  { w: "interessant", a: "", e: "Das Buch ist sehr interessant.", t: "interesting", c: "Adjektive" },
  { w: "kurz", a: "", e: "Das Meeting war kurz.", t: "short / brief", c: "Adjektive" },
  { w: "lang", a: "", e: "Das war ein langer Tag.", t: "long", c: "Adjektive" },
  { w: "leer", a: "", e: "Die Flasche ist leer.", t: "empty", c: "Adjektive" },
  { w: "ledig", a: "", e: "Ich bin ledig.", t: "single (unmarried)", c: "Adjektive" },
  { w: "lieb", a: "", e: "Das ist sehr lieb von Ihnen.", t: "kind / dear", c: "Adjektive" },
  { w: "lustig", a: "", e: "Der Film war sehr lustig.", t: "funny / fun", c: "Adjektive" },
  { w: "möglich", a: "", e: "Ist das möglich?", t: "possible", c: "Adjektive" },
  { w: "nett", a: "", e: "Sie ist sehr nett.", t: "nice / kind", c: "Adjektive" },
  { w: "offen", a: "", e: "Das Geschäft ist offen.", t: "open", c: "Adjektive" },
  { w: "pünktlich", a: "", e: "Der Zug ist pünktlich.", t: "on time / punctual", c: "Adjektive" },
  { w: "sauber", a: "", e: "Das Zimmer ist sauber.", t: "clean", c: "Adjektive" },
  { w: "scharf", a: "", e: "Das Essen ist zu scharf.", t: "spicy / sharp", c: "Adjektive" },
  { w: "süß", a: "", e: "Das Baby ist süß.", t: "sweet / cute", c: "Adjektive" },
  { w: "toll", a: "", e: "Das ist wirklich toll!", t: "great / fantastic", c: "Adjektive" },
  { w: "verheiratet", a: "", e: "Er ist verheiratet.", t: "married", c: "Adjektive" },

  // Sonstiges — weitere Wörter
  { w: "Antwort", a: "die", e: "Ich weiß die Antwort nicht.", t: "answer / reply", c: "Sonstiges" },
  { w: "Beispiel", a: "das", e: "Zum Beispiel Deutsch lernen.", t: "example", c: "Sonstiges" },
  { w: "Ding", a: "das", e: "Was ist das für ein Ding?", t: "thing", c: "Sonstiges" },
  { w: "Farbe", a: "die", e: "Welche Farbe ist das?", t: "colour", c: "Sonstiges" },
  { w: "Frage", a: "die", e: "Ich habe eine Frage.", t: "question", c: "Sonstiges" },
  { w: "Gespräch", a: "das", e: "Wir haben ein Gespräch geführt.", t: "conversation", c: "Sonstiges" },
  { w: "Glück", a: "das", e: "Ich wünsche dir viel Glück!", t: "luck / happiness", c: "Sonstiges" },
  { w: "Grund", a: "der", e: "Aus welchem Grund?", t: "reason", c: "Sonstiges" },
  { w: "Idee", a: "die", e: "Das ist eine gute Idee!", t: "idea", c: "Sonstiges" },
  { w: "Land", a: "das", e: "In welchem Land leben Sie?", t: "country", c: "Sonstiges" },
  { w: "Leute", a: "die", e: "Die Leute hier sind freundlich.", t: "people", c: "Sonstiges" },
  { w: "Mensch", a: "der", e: "Der Mensch ist ein soziales Wesen.", t: "person / human", c: "Sonstiges" },
  { w: "Möglichkeit", a: "die", e: "Es gibt eine Möglichkeit.", t: "possibility / option", c: "Sonstiges" },
  { w: "Plan", a: "der", e: "Was ist dein Plan?", t: "plan", c: "Sonstiges" },
  { w: "Problem", a: "das", e: "Ich habe ein Problem.", t: "problem", c: "Sonstiges" },
  { w: "Sache", a: "die", e: "Das ist meine Sache.", t: "thing / matter", c: "Sonstiges" },
  { w: "Welt", a: "die", e: "Die Welt ist groß.", t: "world", c: "Sonstiges" },
  { w: "etwas", a: "", e: "Kann ich etwas helfen?", t: "something", c: "Sonstiges" },
  { w: "leider", a: "", e: "Leider kann ich nicht kommen.", t: "unfortunately", c: "Sonstiges" },
  { w: "manchmal", a: "", e: "Manchmal gehe ich ins Kino.", t: "sometimes", c: "Sonstiges" },
  { w: "natürlich", a: "", e: "Natürlich helfe ich dir!", t: "of course / naturally", c: "Sonstiges" },
  { w: "nie", a: "", e: "Ich trinke nie Alkohol.", t: "never", c: "Sonstiges" },
  { w: "oft", a: "", e: "Ich gehe oft ins Café.", t: "often", c: "Sonstiges" },
  { w: "oder", a: "", e: "Möchten Sie Kaffee oder Tee?", t: "or", c: "Sonstiges" },
  { w: "schon", a: "", e: "Ich bin schon fertig.", t: "already", c: "Sonstiges" },
  { w: "selten", a: "", e: "Ich esse selten Fast Food.", t: "rarely / seldom", c: "Sonstiges" },
  { w: "sofort", a: "", e: "Ich komme sofort.", t: "immediately", c: "Sonstiges" },
  { w: "vielleicht", a: "", e: "Vielleicht komme ich morgen.", t: "perhaps / maybe", c: "Sonstiges" },
  { w: "weil", a: "", e: "Ich lerne Deutsch, weil ich in Deutschland arbeite.", t: "because", c: "Sonstiges" },
  { w: "wenn", a: "", e: "Wenn du Zeit hast, ruf mich an.", t: "when / if", c: "Sonstiges" },


];

export const emailPrompts = [
  {
    scenario: "Ihr Freund Thomas lädt Sie per E-Mail zu seiner Geburtstagsparty ein.",
    instruction: "Schreiben Sie Thomas eine Antwort. Schreiben Sie zu drei Punkten:",
    points: ["Dank für die Einladung", "kommen Sie? (wann?)", "was bringen Sie mit?"],
  },
  {
    scenario: "Sie haben einen Arzttermin am Montag um 10 Uhr, können aber nicht kommen.",
    instruction: "Schreiben Sie dem Arzt eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Entschuldigung — warum können Sie nicht kommen?", "bitten Sie um einen neuen Termin", "wann haben Sie Zeit?"],
  },
  {
    scenario: "Sie möchten einen Deutschkurs machen. Sie haben die Webseite einer Sprachschule gefunden.",
    instruction: "Schreiben Sie der Sprachschule eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Wann beginnt der Kurs?", "wie viel kostet er?", "gibt es noch freie Plätze?"],
  },
  {
    scenario: "In Ihrer Wohnung ist die Heizung kaputt. Es ist sehr kalt.",
    instruction: "Schreiben Sie Ihrem Vermieter eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Problem beschreiben", "seit wann ist die Heizung kaputt?", "bitten Sie um schnelle Hilfe"],
  },
  {
    scenario: "Ihre Freundin Mia hat Ihnen ein Geschenk zum Geburtstag geschickt.",
    instruction: "Schreiben Sie Mia eine Antwort. Schreiben Sie zu drei Punkten:",
    points: ["Dank für das Geschenk", "wie finden Sie es?", "laden Sie Mia zum Kaffee ein"],
  },
  {
    scenario: "Sie möchten die Prüfung Goethe-Zertifikat A1 ablegen.",
    instruction: "Schreiben Sie dem Goethe-Institut eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["wann findet die Prüfung statt?", "wie viel kostet die Anmeldung?", "wie können Sie sich anmelden?"],
  },
  {
    scenario: "Sie möchten Ihren Kollegen Leon nach der Arbeit zum Kaffee einladen.",
    instruction: "Schreiben Sie Leon eine kurze Nachricht. Schreiben Sie zu drei Punkten:",
    points: ["Einladung (wann und wohin?)", "warum möchten Sie sich treffen?", "bitten Sie um eine Antwort"],
  },
  {
    scenario: "Ihr Kind ist krank und kann heute nicht in die Schule gehen.",
    instruction: "Schreiben Sie der Lehrerin eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Ihr Kind kommt heute nicht", "warum? (was ist das Problem?)", "wann kommt es wieder?"],
  },
  {
    scenario: "Sie möchten ins Schwimmbad gehen und haben Fragen.",
    instruction: "Schreiben Sie dem Schwimmbad eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Wann hat das Schwimmbad geöffnet?", "was kostet der Eintritt?", "gibt es Kurse für Erwachsene?"],
  },
  {
    scenario: "Sie kommen zu einem Treffen mit Ihrem Freund Felix zu spät.",
    instruction: "Schreiben Sie Felix eine kurze Nachricht. Schreiben Sie zu drei Punkten:",
    points: ["Entschuldigung — Sie kommen zu spät", "warum?", "wann kommen Sie an?"],
  },
  {
    scenario: "Sie möchten ein Hotelzimmer für Ihren Urlaub buchen.",
    instruction: "Schreiben Sie dem Hotel eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["wann möchten Sie kommen? (wie viele Nächte?)", "Einzel- oder Doppelzimmer?", "was kostet das Zimmer? (mit Frühstück?)"],
  },
  {
    scenario: "Sie haben eine neue Wohnung und möchten Ihren Freund Ben einladen.",
    instruction: "Schreiben Sie Ben eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Beschreibung der Wohnung (Zimmer, Lage)", "was gefällt Ihnen an der Wohnung?", "laden Sie Ben zur Besichtigung ein"],
  },
];

export const wfQuestions = [
  { q: "___ heißen Sie?", a: "Wie", o: ["Wo", "Wie", "Was", "Wann"] },
  { q: "___ wohnen Sie?", a: "Wo", o: ["Wer", "Was", "Wo", "Warum"] },
  { q: "___ kommen Sie?", a: "Woher", o: ["Woher", "Wohin", "Wo", "Wann"] },
  { q: "___ beginnt der Kurs?", a: "Wann", o: ["Was", "Wo", "Wann", "Wer"] },
  { q: "___ kostet das?", a: "Wie viel", o: ["Was", "Wie viel", "Wann", "Wo"] },
  { q: "___ ist das?", a: "Wer", o: ["Wer", "Wo", "Was", "Wie"] },
  { q: "___ lernst du Deutsch?", a: "Warum", o: ["Wann", "Warum", "Wie", "Wo"] },
  { q: "___ fährst du am Wochenende?", a: "Wohin", o: ["Woher", "Wo", "Wann", "Wohin"] },
  { q: "___ Sprachen sprechen Sie?", a: "Welche", o: ["Was", "Welche", "Wie", "Wann"] },
  { q: "___ alt sind Sie?", a: "Wie", o: ["Was", "Wo", "Wie", "Wer"] },
  { q: "___ machst du heute?", a: "Was", o: ["Wer", "Was", "Wo", "Wann"] },
  { q: "___ geht es Ihnen?", a: "Wie", o: ["Wie", "Was", "Wo", "Wer"] },
  { q: "___ kommt der nächste Bus?", a: "Wann", o: ["Wo", "Wann", "Was", "Wer"] },
  { q: "___ ist die Toilette?", a: "Wo", o: ["Was", "Wer", "Wo", "Wie"] },
  { q: "___ möchten Sie trinken?", a: "Was", o: ["Wie", "Was", "Wo", "Wer"] },
  { q: "___ Kinder haben Sie?", a: "Wie viele", o: ["Was", "Wann", "Wie viele", "Welche"] },
  { q: "___ ist Ihr Beruf?", a: "Was", o: ["Wer", "Was", "Wie", "Wann"] },
  { q: "___ Buch möchtest du?", a: "Welches", o: ["Was", "Welches", "Wie", "Wo"] },
  { q: "___ kommt er nicht?", a: "Warum", o: ["Wann", "Warum", "Wie", "Wo"] },
];

export const schedule = [
  { d: 1, f: "Decoding", t: "Go through flashcards. Mark words you don't know." },
  { d: 2, f: "Decoding", t: "Continue flashcards. Focus on 'Don't Know' words." },
  { d: 3, f: "Decoding", t: "Final pass through unknown words. Use Word List to review." },
  { d: 4, f: "Patterns", t: "Study Grammar tab. Watch A1 Speaking Exam videos on YouTube." },
  { d: 5, f: "Patterns", t: "Practice Speaking Simulator. Note exact phrases." },
  { d: 6, f: "Patterns", t: "Master W-Fragen quiz. Review email templates." },
  { d: 7, f: "Simulations", t: "Do practice test set 1 (Goethe website). Time yourself." },
  { d: 8, f: "Simulations", t: "Do practice test set 2. Review mistakes." },
  { d: 9, f: "Simulations", t: "Do practice test set 3. Focus on listening (catch the nouns!)." },
  { d: 10, f: "Simulations", t: "Review all wrong answers. Drill weak categories." },
  { d: 11, f: "Production", t: "Write 2 practice emails. Self-Intro 5 times." },
  { d: 12, f: "Production", t: "Write 2 more emails. Self-Intro 5 more times. Speaking cards." },
  { d: 13, f: "Production", t: "Final email. Self-Intro 10 times. Full speaking run-through." },
  { d: 14, f: "Rest", t: "Review Grammar cheat sheet & email templates only. You got this." },
];

// ===== HÖREN DATA =====
// Part 1: Short dialogues → multiple choice (which answer is correct?)
// Part 2: Short messages → write the key info (number, time, name)
// Part 3: Public announcements → Richtig oder Falsch?
export const hoerenData = {
  teil1: [
    {
      script: [
        { s: 'Kunde', t: 'Guten Morgen! Ich möchte gerne einen Termin beim Zahnarzt.' },
        { s: 'Rezeption', t: 'Natürlich. Wann passt Ihnen der Termin?' },
        { s: 'Kunde', t: 'Am Dienstag, wenn möglich.' },
        { s: 'Rezeption', t: 'Dienstag um zehn Uhr ist noch frei.' },
      ],
      question: 'Was möchte der Kunde?',
      options: ['Einen Termin beim Zahnarzt', 'Eine Fahrkarte kaufen', 'Ein Hotelzimmer buchen'],
      answer: 0,
    },
    {
      script: [
        { s: 'Anna', t: 'Entschuldigung, ich suche die Bibliothek. Können Sie mir helfen?' },
        { s: 'Mann', t: 'Ja, gerne. Gehen Sie hier geradeaus und dann links.' },
        { s: 'Anna', t: 'Und wie weit ist das?' },
        { s: 'Mann', t: 'Ungefähr fünf Minuten zu Fuß.' },
      ],
      question: 'Wohin möchte Anna?',
      options: ['Zum Supermarkt', 'Zur Bibliothek', 'Zum Bahnhof'],
      answer: 1,
    },
    {
      script: [
        { s: 'Tom', t: 'Ich möchte ein Kilo Äpfel und zwei Liter Milch, bitte.' },
        { s: 'Verkäuferin', t: 'Hier bitte. Das macht zusammen drei Euro fünfzig.' },
        { s: 'Tom', t: 'Haben Sie auch Bananen heute?' },
        { s: 'Verkäuferin', t: 'Nein, die haben wir heute leider nicht.' },
      ],
      question: 'Was kauft Tom?',
      options: ['Äpfel und Bananen', 'Äpfel und Milch', 'Milch und Bananen'],
      answer: 1,
    },
    {
      script: [
        { s: 'Mia', t: 'Wann fährt der nächste Zug nach Frankfurt?' },
        { s: 'Information', t: 'Der nächste Zug fährt um vierzehn Uhr dreißig von Gleis drei.' },
        { s: 'Mia', t: 'Und wie lange dauert die Fahrt?' },
        { s: 'Information', t: 'Ungefähr zwei Stunden.' },
      ],
      question: 'Um wie viel Uhr fährt der Zug?',
      options: ['13:30 Uhr', '14:30 Uhr', '15:30 Uhr'],
      answer: 1,
    },
    {
      script: [
        { s: 'Lena', t: 'Ich suche einen Deutschkurs für Anfänger. Wann beginnt der nächste Kurs?' },
        { s: 'Sekretärin', t: 'Der nächste Anfängerkurs beginnt am Montag, dem dritten März.' },
        { s: 'Lena', t: 'Und wie viel kostet er?' },
        { s: 'Sekretärin', t: 'Er kostet hundertfünfzig Euro für acht Wochen.' },
      ],
      question: 'Wann beginnt der Kurs?',
      options: ['Am Montag, 3. März', 'Am Mittwoch, 3. März', 'Am Montag, 13. März'],
      answer: 0,
    },
  ],
  teil2: [
    {
      script: 'Hallo, hier ist Sandra Berger. Ich kann heute Abend leider nicht kommen — ich bin krank. Können wir den Termin auf Freitag verschieben? Ruf mich bitte zurück. Meine Nummer ist null-eins-sieben-sechs, drei-vier-fünf-sechs-sieben-acht.',
      question: 'Auf welchen Tag möchte Sandra den Termin verschieben?',
      answer: 'Freitag',
      hint: 'Wochentag',
    },
    {
      script: 'Guten Tag, hier ist das Kurszentrum Mitte. Ihr Deutschkurs beginnt am Montag um achtzehn Uhr dreißig in Raum zwölf. Bitte bringen Sie Ihren Ausweis und ein Heft mit.',
      question: 'Um wie viel Uhr beginnt der Kurs?',
      answer: '18:30',
      hint: 'Uhrzeit',
    },
    {
      script: 'Hier ist eine Nachricht für Herrn Müller. Ihr Termin beim Zahnarzt ist am Donnerstag, dem achten April um neun Uhr fünfzehn. Die Praxis ist in der Hauptstraße zweiundzwanzig.',
      question: 'Wie lautet die Hausnummer der Praxis?',
      answer: '22',
      hint: 'Nummer',
    },
    {
      script: 'Hallo Peter, hier ist deine Schwester Julia. Kannst du bitte fünf Kilogramm Mehl und drei Liter Öl kaufen? Ich koche heute Abend für die ganze Familie. Danke!',
      question: 'Wie viel Mehl soll Peter kaufen?',
      answer: '5 kg',
      hint: 'Menge',
    },
    {
      script: 'Achtung, liebe Fahrgäste! Der Intercity eins-sieben-null nach Hamburg hat heute eine Verspätung von zwanzig Minuten. Neue Abfahrtszeit ist elf Uhr fünfzehn von Gleis sechs.',
      question: 'Wie viele Minuten Verspätung hat der Zug?',
      answer: '20',
      hint: 'Minuten',
    },
  ],
  teil3: [
    {
      script: 'Sehr geehrte Kunden! Unser Supermarkt ist heute wegen Inventur um achtzehn Uhr geschlossen. Morgen öffnen wir wieder um acht Uhr. Wir bitten um Ihr Verständnis.',
      statement: 'Der Supermarkt schließt heute früher als normal.',
      answer: true,
    },
    {
      script: 'Liebe Fahrgäste, die U-Bahn Linie U4 fährt heute zwischen Hauptbahnhof und Stadtmitte nicht. Bitte benutzen Sie den Ersatzbus. Wir entschuldigen uns für die Unannehmlichkeiten.',
      statement: 'Die U4 fährt heute auf der ganzen Strecke normal.',
      answer: false,
    },
    {
      script: 'Herzlich willkommen im Schwimmbad Westpark! Das Hallenbad ist täglich von sieben bis zweiundzwanzig Uhr geöffnet. Der Eintritt kostet vier Euro für Erwachsene und zwei Euro für Kinder.',
      statement: 'Kinder zahlen weniger Eintritt als Erwachsene.',
      answer: true,
    },
    {
      script: 'Achtung, wichtige Durchsage! Im dritten Stock des Kaufhauses gibt es heute ein Sonderangebot: Alle Winterjacken sind fünfzig Prozent günstiger. Das Angebot gilt nur heute!',
      statement: 'Das Angebot für Winterjacken gilt eine ganze Woche.',
      answer: false,
    },
    {
      script: 'Guten Tag! Das Stadtmuseum ist ab nächster Woche mittwochs bis sonntags geöffnet. Montags und dienstags bleibt es geschlossen. Der Eintritt ist kostenlos. Wir freuen uns auf Ihren Besuch!',
      statement: 'Der Eintritt ins Stadtmuseum ist gratis.',
      answer: true,
    },
  ],
};

// ===== LESEN DATA =====
// Part 1: Match people (with needs) to the correct ad/notice
// Part 2: Read a text → Richtig oder Falsch?
// Part 3: Read an info text → fill in a form
export const lesenData = [
  {
    teil1: {
      people: [
        { name: 'Herr Berger', need: 'Er sucht einen Sprachkurs für Anfänger am Abend.' },
        { name: 'Frau Schmidt', need: 'Sie möchte ihr altes Fahrrad verkaufen.' },
        { name: 'Yuki', need: 'Sie sucht eine Mitbewohnerin für ihre Wohnung.' },
        { name: 'Marco', need: 'Er möchte am Wochenende Fußball spielen.' },
        { name: 'Fatima', need: 'Sie sucht günstige Nachhilfe in Mathe.' },
      ],
      ads: [
        { label: 'A', title: 'Spanischkurs Anfänger', text: 'Montag & Mittwoch, 18–20 Uhr. VHS Weststadt. 80 € / Monat.' },
        { label: 'B', title: 'WG-Zimmer zu vergeben', text: 'Suche Mitbewohnerin ab 1. März. Zimmer 15 m², 450 € warm. Nichtraucher.' },
        { label: 'C', title: 'Fahrrad zu verkaufen', text: 'Damenrad, blau, 7 Gang, guter Zustand. Preis: 80 €. Tel: 0176-123456.' },
        { label: 'D', title: 'Fußball am Wochenende', text: 'Hobby-Team sucht Spieler! Samstags 10 Uhr im Stadtpark. Anfänger willkommen.' },
        { label: 'E', title: 'Mathenachhilfe', text: 'Studentin gibt Nachhilfe in Mathematik. 10 € / Stunde. Alle Klassenstufen.' },
        { label: 'F', title: 'Deutschkurs für Anfänger', text: 'Dienstag & Donnerstag, 19–21 Uhr. Nur 60 € im Monat. Kleine Gruppen!' },
        { label: 'G', title: 'Fahrrad kaufen', text: 'Suche gebrauchtes Herrenrad, max. 100 €. Tel: 0170-555666.' },
      ],
      answers: { 'Herr Berger': 'F', 'Frau Schmidt': 'C', 'Yuki': 'B', 'Marco': 'D', 'Fatima': 'E' },
    },
    teil2: {
      text: 'Liebe Frau Hoffmann,\n\nvielen Dank für Ihre E-Mail. Ich freue mich, dass Sie an unserem Deutschkurs interessiert sind.\n\nDer Kurs A1.1 beginnt am Montag, dem 5. März und endet am 30. April. Er findet montags und mittwochs von 9 bis 11 Uhr statt. Der Kursraum ist im zweiten Stock, Zimmer 204.\n\nDie Kursgebühr beträgt 120 Euro. Bitte überweisen Sie den Betrag bis zum 1. März. Sie brauchen das Lernbuch „Schritte Plus Neu A1".\n\nBei Fragen stehe ich gerne zur Verfügung.\n\nMit freundlichen Grüßen\nM. Weber, Kursleitung',
      statements: [
        { text: 'Der Kurs beginnt im Februar.', answer: false },
        { text: 'Der Kurs findet zweimal pro Woche statt.', answer: true },
        { text: 'Der Kursraum ist im dritten Stock.', answer: false },
        { text: 'Der Kurs kostet 120 Euro.', answer: true },
        { text: 'Man braucht ein Lernbuch für den Kurs.', answer: true },
      ],
    },
    teil3: {
      text: 'Vorname: Maria\nFamilienname: Santos\nGeburtsdatum: 14.06.1995\nGeburtsort: Lissabon\nNationalität: portugiesisch\nBeruf: Krankenpflegerin\nAdresse: Gartenstraße 8, 80333 München\nTelefon: 0176-223344\nGewünschter Kurs: Deutsch A1',
      instruction: 'Lesen Sie die Information und füllen Sie das Formular aus.',
      fields: [
        { label: 'Familienname', answer: 'Santos' },
        { label: 'Geburtsdatum', answer: '14.06.1995' },
        { label: 'Nationalität', answer: 'portugiesisch' },
        { label: 'Beruf', answer: 'Krankenpflegerin' },
        { label: 'Telefon', answer: '0176-223344' },
      ],
    },
  },
  {
    teil1: {
      people: [
        { name: 'Frau Klein', need: 'Sie sucht eine günstige Wohnung zur Miete.' },
        { name: 'Ali', need: 'Er sucht Arbeit als Koch.' },
        { name: 'Suna', need: 'Sie braucht abends einen Babysitter.' },
        { name: 'Herr Vogel', need: 'Er möchte seinen Computer reparieren lassen.' },
        { name: 'Lara', need: 'Sie sucht einen Yogakurs für Anfänger.' },
      ],
      ads: [
        { label: 'A', title: 'Yoga für Anfänger', text: 'Jeden Dienstag, 17–18:30 Uhr. Gemeinschaftszentrum Nord. 30 € / Monat.' },
        { label: 'B', title: '2-Zimmer-Wohnung', text: '55 m², ruhige Lage, ab 1.4. frei. 650 € warm. Kontakt: 089-334455.' },
        { label: 'C', title: 'Koch gesucht', text: 'Restaurant „Zum Löwen" sucht erfahrenen Koch. Vollzeit, sofort. Bewerbung: info@zumloewen.de.' },
        { label: 'D', title: 'PC-Reparatur', text: 'Schnell und günstig! Laptop, PC, Drucker reparieren. Hausbesuch möglich. Tel: 0178-112233.' },
        { label: 'E', title: 'Babysitter angeboten', text: 'Biete Babysitting für Kleinkinder, auch abends. Erfahrung vorhanden. 10 € / Stunde.' },
        { label: 'F', title: 'Pilates-Kurs', text: 'Mittwochs 18 Uhr. Fitness Center Mitte. 40 € monatlich.' },
        { label: 'G', title: 'Büro zu vermieten', text: '30 m², Erdgeschoss, gute Anbindung. 500 € netto.' },
      ],
      answers: { 'Frau Klein': 'B', 'Ali': 'C', 'Suna': 'E', 'Herr Vogel': 'D', 'Lara': 'A' },
    },
    teil2: {
      text: 'Hallo Tomás!\n\nWie geht es dir? Ich bin jetzt seit drei Monaten in Berlin und es gefällt mir sehr gut. Ich wohne in Mitte — das ist das Zentrum der Stadt. Meine Wohnung hat zwei Zimmer. Sie ist nicht sehr groß, aber ich habe alles, was ich brauche.\n\nIch arbeite in einem Café. Die Arbeit macht mir Spaß, aber manchmal ist es sehr stressig. Meine Kollegen sind sehr nett.\n\nAm Wochenende gehe ich oft in den Park oder ins Museum. Berlin hat so viele interessante Museen! Und du? Was machst du gerade?\n\nViele Grüße\nAnna',
      statements: [
        { text: 'Anna wohnt seit einem Jahr in Berlin.', answer: false },
        { text: 'Anna wohnt im Zentrum von Berlin.', answer: true },
        { text: 'Ihre Wohnung hat drei Zimmer.', answer: false },
        { text: 'Anna arbeitet in einem Café.', answer: true },
        { text: 'Am Wochenende geht Anna manchmal ins Museum.', answer: true },
      ],
    },
    teil3: {
      text: 'Kursleiter: Thomas Bauer\nKursname: Gitarre für Anfänger\nKursnummer: MU-401\nBeginn: 10. September\nEnde: 15. Dezember\nTag: Donnerstag\nUhrzeit: 16:00–17:30 Uhr\nKursraum: Raum 15\nMaximale Teilnehmerzahl: 8 Personen\nGebühr: 95 Euro pro Kurshalbjahr',
      instruction: 'Lesen Sie die Kursinformation und füllen Sie das Formular aus.',
      fields: [
        { label: 'Kursleiter', answer: 'Thomas Bauer' },
        { label: 'Beginn des Kurses', answer: '10. September' },
        { label: 'Wochentag', answer: 'Donnerstag' },
        { label: 'Uhrzeit', answer: '16:00–17:30 Uhr' },
        { label: 'Gebühr', answer: '95 Euro' },
      ],
    },
  },
  {
    teil1: {
      people: [
        { name: 'Herr Park', need: 'Er sucht einen Arzt für seine kranke Katze.' },
        { name: 'Lisa', need: 'Sie möchte ein Zimmer in einer WG mieten.' },
        { name: 'Omar', need: 'Er sucht einen Nebenjob am Wochenende.' },
        { name: 'Frau Torres', need: 'Sie sucht einen Kochkurs für Anfänger.' },
        { name: 'Ben', need: 'Er möchte seinen Fernseher verkaufen.' },
      ],
      ads: [
        { label: 'A', title: 'Tierarzt Dr. Neumann', text: 'Kleintierpraxis. Hunde, Katzen, Vögel. Mo–Fr 8–18 Uhr. Notdienst: 0800-TIER.' },
        { label: 'B', title: 'WG-Zimmer gesucht', text: 'Suche Zimmer in WG, max. 400 € warm. Nichtraucher, ordentlich. Tel: 0157-998877.' },
        { label: 'C', title: 'WG-Zimmer frei', text: 'Zimmer in 3er-WG, 12 m², 380 € warm. Zentrumsnähe. Frei ab sofort. Kontakt per E-Mail.' },
        { label: 'D', title: 'Kellner/in gesucht', text: 'Restaurant im Zentrum sucht Aushilfe am Wochenende. Gute Bezahlung. Bitte melden: 089-224466.' },
        { label: 'E', title: 'Kochen für Einsteiger', text: 'VHS-Kurs: Grundlagen der Küche. Samstags 10–13 Uhr. 5 Termine, 55 Euro.' },
        { label: 'F', title: 'Fernseher zu verkaufen', text: '55 Zoll, Full HD, guter Zustand. 150 €. Selbstabholung. Tel: 0176-667788.' },
        { label: 'G', title: 'Babysitter gesucht', text: 'Familie sucht Babysitter für 2 Kinder, freitags 18–22 Uhr. 12 € / Stunde.' },
      ],
      answers: { 'Herr Park': 'A', 'Lisa': 'C', 'Omar': 'D', 'Frau Torres': 'E', 'Ben': 'F' },
    },
    teil2: {
      text: 'Liebe Eltern und Erziehungsberechtigte,\n\nwir möchten Sie darüber informieren, dass unsere Schule am Freitag, dem 22. März, wegen eines Lehrerfortbildungstages geschlossen ist. Der Unterricht beginnt wieder am Montag, dem 25. März, wie gewohnt um 8 Uhr.\n\nAm 10. April findet unser Schulfest statt. Alle Familien sind herzlich eingeladen! Das Fest beginnt um 14 Uhr auf dem Schulhof. Bei schlechtem Wetter findet es in der Turnhalle statt.\n\nBei Fragen wenden Sie sich bitte an das Sekretariat.\n\nMit freundlichen Grüßen\nDie Schulleitung',
      statements: [
        { text: 'Die Schule ist am Freitag geöffnet.', answer: false },
        { text: 'Am Montag beginnt der Unterricht um 8 Uhr.', answer: true },
        { text: 'Das Schulfest findet am 10. März statt.', answer: false },
        { text: 'Das Schulfest beginnt um 14 Uhr.', answer: true },
        { text: 'Bei Regen findet das Fest in der Turnhalle statt.', answer: true },
      ],
    },
    teil3: {
      text: 'Mitgliedsantrag Sportverein Blau-Weiß München\nVorname: Kenji\nFamilienname: Tanaka\nGeburtsdatum: 03.11.2000\nNationalität: japanisch\nAdresse: Rosenweg 14, 81234 München\nTelefon: 0179-445566\nE-Mail: k.tanaka@mail.de\nGewünschte Sportart: Tennis\nMitgliedsbeitrag: 25 Euro / Monat',
      instruction: 'Lesen Sie den Mitgliedsantrag und füllen Sie das Formular aus.',
      fields: [
        { label: 'Vorname', answer: 'Kenji' },
        { label: 'Geburtsdatum', answer: '03.11.2000' },
        { label: 'Adresse', answer: 'Rosenweg 14, 81234 München' },
        { label: 'Sportart', answer: 'Tennis' },
        { label: 'Monatsbeitrag', answer: '25 Euro' },
      ],
    },
  },
];

// ===== SCHREIBEN TEIL 2 — FORM DATA =====
export const formData = [
  {
    title: 'Anmeldeformular — Sprachschule',
    scenario: 'Sie möchten sich für einen Deutschkurs anmelden. Füllen Sie das Formular aus.',
    fields: [
      { label: 'Familienname', placeholder: 'Ihr Nachname' },
      { label: 'Vorname', placeholder: 'Ihr Vorname' },
      { label: 'Geburtsdatum', placeholder: 'TT.MM.JJJJ' },
      { label: 'Geburtsland', placeholder: 'z. B. Indien' },
      { label: 'Adresse', placeholder: 'Straße Nr., PLZ Ort' },
      { label: 'Telefonnummer', placeholder: '0...' },
    ],
  },
  {
    title: 'Kontaktformular — Arztpraxis',
    scenario: 'Sie möchten einen Termin beim Arzt. Füllen Sie die Kontaktdaten aus.',
    fields: [
      { label: 'Name', placeholder: 'Vor- und Nachname' },
      { label: 'Geburtsdatum', placeholder: 'TT.MM.JJJJ' },
      { label: 'Telefon', placeholder: '0...' },
      { label: 'Krankenkasse', placeholder: 'z. B. AOK, TK, DAK' },
      { label: 'Grund des Termins', placeholder: 'z. B. Erkältung, Rückenschmerzen' },
    ],
  },
  {
    title: 'Vereinsmitgliedschaft — Sportverein',
    scenario: 'Sie möchten Mitglied in einem Sportverein werden. Füllen Sie das Formular aus.',
    fields: [
      { label: 'Familienname', placeholder: 'Ihr Nachname' },
      { label: 'Vorname', placeholder: 'Ihr Vorname' },
      { label: 'Geburtsdatum', placeholder: 'TT.MM.JJJJ' },
      { label: 'E-Mail-Adresse', placeholder: 'ihre@email.de' },
      { label: 'Gewünschte Sportart', placeholder: 'z. B. Fußball, Tennis, Schwimmen' },
    ],
  },
];

// ===== SPRECHEN DATA (Mock Exam Teil 2 & 3) =====
export const sprechenData = {
  // Teil 2: Name an object shown on a card
  teil2: [
    { w: 'Apfel', a: 'der', hint: 'Das ist ein Apfel. / Ich sehe einen Apfel.' },
    { w: 'Buch', a: 'das', hint: 'Das ist ein Buch. / Ich sehe ein Buch.' },
    { w: 'Stuhl', a: 'der', hint: 'Das ist ein Stuhl. / Ich sehe einen Stuhl.' },
    { w: 'Tasche', a: 'die', hint: 'Das ist eine Tasche. / Ich sehe eine Tasche.' },
    { w: 'Handy', a: 'das', hint: 'Das ist ein Handy. / Ich sehe ein Handy.' },
  ],
  // Teil 3: Make a request / ask for something based on a picture
  teil3: [
    {
      picture: '🚌 Bushaltestelle',
      situation: 'Sie sind an der Bushaltestelle. Fragen Sie nach dem Bus.',
      templates: [
        'Wann kommt der nächste Bus?',
        'Fährt der Bus zum Hauptbahnhof?',
        'Wie viel kostet die Fahrkarte?',
      ],
    },
    {
      picture: '🍽️ Restaurant',
      situation: 'Sie sind im Restaurant. Bestellen Sie etwas.',
      templates: [
        'Ich möchte gerne [Gericht], bitte.',
        'Haben Sie [Gericht]?',
        'Was können Sie empfehlen?',
        'Die Speisekarte, bitte.',
      ],
    },
    {
      picture: '🏪 Supermarkt',
      situation: 'Sie sind im Supermarkt und suchen ein Produkt.',
      templates: [
        'Entschuldigung, wo finde ich [Produkt]?',
        'Haben Sie [Produkt]?',
        'Was kostet das?',
      ],
    },
    {
      picture: '🏥 Arztpraxis',
      situation: 'Sie sind beim Arzt. Beschreiben Sie Ihr Problem.',
      templates: [
        'Ich habe Schmerzen im/in der [Körperteil].',
        'Mir ist nicht gut.',
        'Ich habe seit [Zeit] Fieber.',
        'Ich brauche ein Rezept für [Medikament].',
      ],
    },
    {
      picture: '🏨 Hotel',
      situation: 'Sie möchten ein Zimmer im Hotel buchen.',
      templates: [
        'Ich möchte ein Einzelzimmer für [Anzahl] Nächte.',
        'Was kostet das Zimmer pro Nacht?',
        'Ist das Frühstück inbegriffen?',
        'Haben Sie ein Zimmer frei?',
      ],
    },
  ],
};
