// Goethe A1 Wortliste - official word list for Start Deutsch 1
// Each entry: { w: word, a: article (der/die/das or ""), e: example sentence, t: English translation, c: category }

export const words = [
  // Zahlen
  { w: "eins", a: "", e: "Ich habe eins.", t: "one", c: "Zahlen" },
  { w: "zwei", a: "", e: "Zwei Kaffee, bitte.", t: "two", c: "Zahlen" },
  { w: "drei", a: "", e: "Ich habe drei Kinder.", t: "three", c: "Zahlen" },
  { w: "vier", a: "", e: "Um vier Uhr.", t: "four", c: "Zahlen" },
  { w: "fünf", a: "", e: "Fünf Euro, bitte.", t: "five", c: "Zahlen" },
  { w: "sechs", a: "", e: "Sechs Uhr morgens.", t: "six", c: "Zahlen" },
  { w: "sieben", a: "", e: "Sieben Tage die Woche.", t: "seven", c: "Zahlen" },
  { w: "acht", a: "", e: "Um acht Uhr beginnt der Kurs.", t: "eight", c: "Zahlen" },
  { w: "neun", a: "", e: "Neun Uhr.", t: "nine", c: "Zahlen" },
  { w: "zehn", a: "", e: "Zehn Euro.", t: "ten", c: "Zahlen" },
  { w: "zwanzig", a: "", e: "Ich bin zwanzig Jahre alt.", t: "twenty", c: "Zahlen" },
  { w: "hundert", a: "", e: "Das kostet hundert Euro.", t: "hundred", c: "Zahlen" },
  { w: "tausend", a: "", e: "Eintausend Kilometer.", t: "thousand", c: "Zahlen" },

  // Zeit
  { w: "Sekunde", a: "die", e: "Einen Moment, eine Sekunde bitte.", t: "second", c: "Zeit" },
  { w: "Minute", a: "die", e: "Der Zug kommt in fünf Minuten.", t: "minute", c: "Zeit" },
  { w: "Stunde", a: "die", e: "Ich bin in einer Stunde zurück.", t: "hour", c: "Zeit" },
  { w: "Tag", a: "der", e: "Heute ist ein schöner Tag.", t: "day", c: "Zeit" },
  { w: "Woche", a: "die", e: "Sehen wir uns nächste Woche?", t: "week", c: "Zeit" },
  { w: "Jahr", a: "das", e: "Ein gutes neues Jahr!", t: "year", c: "Zeit" },
  { w: "Uhr", a: "die", e: "Es ist vier Uhr.", t: "clock / o'clock", c: "Zeit" },
  { w: "Morgen", a: "der", e: "Guten Morgen!", t: "morning", c: "Zeit" },
  { w: "Vormittag", a: "der", e: "Am Vormittag arbeite ich.", t: "late morning", c: "Zeit" },
  { w: "Mittag", a: "der", e: "Wir essen um zwölf Uhr Mittag.", t: "noon / midday", c: "Zeit" },
  { w: "Nachmittag", a: "der", e: "Am Nachmittag bin ich frei.", t: "afternoon", c: "Zeit" },
  { w: "Abend", a: "der", e: "Guten Abend!", t: "evening", c: "Zeit" },
  { w: "Nacht", a: "die", e: "Gute Nacht!", t: "night", c: "Zeit" },

  // Wochentage
  { w: "Montag", a: "der", e: "Am Montag beginnt der Kurs.", t: "Monday", c: "Wochentage" },
  { w: "Dienstag", a: "der", e: "Dienstag habe ich frei.", t: "Tuesday", c: "Wochentage" },
  { w: "Mittwoch", a: "der", e: "Am Mittwoch gehen wir einkaufen.", t: "Wednesday", c: "Wochentage" },
  { w: "Donnerstag", a: "der", e: "Der Termin ist am Donnerstag.", t: "Thursday", c: "Wochentage" },
  { w: "Freitag", a: "der", e: "Am Freitag machen wir eine Party.", t: "Friday", c: "Wochentage" },
  { w: "Samstag", a: "der", e: "Am Samstag schlafe ich lange.", t: "Saturday", c: "Wochentage" },
  { w: "Sonntag", a: "der", e: "Am Sonntag besuche ich meine Eltern.", t: "Sunday", c: "Wochentage" },
  { w: "Wochenende", a: "das", e: "Am Wochenende fahren wir weg.", t: "weekend", c: "Wochentage" },

  // Monate
  { w: "Januar", a: "der", e: "Im Januar ist es kalt.", t: "January", c: "Monate" },
  { w: "Februar", a: "der", e: "Im Februar schneit es oft.", t: "February", c: "Monate" },
  { w: "März", a: "der", e: "Im März beginnt der Frühling.", t: "March", c: "Monate" },
  { w: "April", a: "der", e: "Im April regnet es viel.", t: "April", c: "Monate" },
  { w: "Mai", a: "der", e: "Im Mai blühen die Blumen.", t: "May", c: "Monate" },
  { w: "Juni", a: "der", e: "Im Juni ist Sommer.", t: "June", c: "Monate" },
  { w: "Juli", a: "der", e: "Im Juli fahren wir in Urlaub.", t: "July", c: "Monate" },
  { w: "August", a: "der", e: "Im August ist es sehr heiß.", t: "August", c: "Monate" },
  { w: "September", a: "der", e: "Im September beginnt die Schule.", t: "September", c: "Monate" },
  { w: "Oktober", a: "der", e: "Im Oktober ist Oktoberfest.", t: "October", c: "Monate" },
  { w: "November", a: "der", e: "Im November ist es dunkel.", t: "November", c: "Monate" },
  { w: "Dezember", a: "der", e: "Im Dezember ist Weihnachten.", t: "December", c: "Monate" },

  // Farben
  { w: "schwarz", a: "", e: "Der Kaffee ist schwarz.", t: "black", c: "Farben" },
  { w: "weiß", a: "", e: "Die Wand ist weiß.", t: "white", c: "Farben" },
  { w: "grau", a: "", e: "Der Himmel ist grau.", t: "gray", c: "Farben" },
  { w: "rot", a: "", e: "Die Tomate ist rot.", t: "red", c: "Farben" },
  { w: "gelb", a: "", e: "Die Banane ist gelb.", t: "yellow", c: "Farben" },
  { w: "blau", a: "", e: "Er hat blaue Augen.", t: "blue", c: "Farben" },
  { w: "grün", a: "", e: "Die Tomate ist noch grün.", t: "green", c: "Farben" },
  { w: "braun", a: "", e: "Der Tisch ist braun.", t: "brown", c: "Farben" },

  // Person
  { w: "Name", a: "der", e: "Mein Name ist Thomas Schmidt.", t: "name", c: "Person" },
  { w: "Vorname", a: "der", e: "Mein Vorname ist Eva.", t: "first name", c: "Person" },
  { w: "Adresse", a: "die", e: "Können Sie mir seine Adresse sagen?", t: "address", c: "Person" },
  { w: "Alter", a: "das", e: "Alter: 26 Jahre.", t: "age", c: "Person" },
  { w: "Geburtstag", a: "der", e: "Herzlichen Glückwunsch zum Geburtstag!", t: "birthday", c: "Person" },
  { w: "Frau", a: "die", e: "Guten Tag, Frau Schmitt!", t: "woman / Mrs.", c: "Person" },
  { w: "Mann", a: "der", e: "Mein Mann arbeitet bei der Polizei.", t: "man / husband", c: "Person" },
  { w: "Kind", a: "das", e: "Wie viele Kinder haben Sie?", t: "child", c: "Person" },
  { w: "Freund", a: "der", e: "Das ist ein Freund von mir.", t: "friend", c: "Person" },
  { w: "Familie", a: "die", e: "Meine Familie lebt in Spanien.", t: "family", c: "Person" },
  { w: "Eltern", a: "die", e: "Meine Eltern leben in Spanien.", t: "parents", c: "Person" },
  { w: "Mutter", a: "die", e: "Das ist die Mutter von Michaela.", t: "mother", c: "Person" },
  { w: "Vater", a: "der", e: "Mein Vater ist Arbeiter.", t: "father", c: "Person" },
  { w: "Sohn", a: "der", e: "Das ist Hans, mein Sohn.", t: "son", c: "Person" },
  { w: "Tochter", a: "die", e: "Das ist meine Tochter Katharina.", t: "daughter", c: "Person" },
  { w: "Bruder", a: "der", e: "Sein Bruder arbeitet auch hier.", t: "brother", c: "Person" },
  { w: "Schwester", a: "die", e: "Meine Schwester kommt am Dienstag.", t: "sister", c: "Person" },
  { w: "Großmutter", a: "die", e: "Meine Großmutter heißt Eva.", t: "grandmother", c: "Person" },
  { w: "Großvater", a: "der", e: "Mein Großvater ist schon 80.", t: "grandfather", c: "Person" },

  // Wohnen
  { w: "Wohnung", a: "die", e: "Seit wann haben Sie diese Wohnung?", t: "apartment", c: "Wohnen" },
  { w: "Haus", a: "das", e: "In welchem Haus wohnst du?", t: "house", c: "Wohnen" },
  { w: "Zimmer", a: "das", e: "Die Wohnung hat drei Zimmer.", t: "room", c: "Wohnen" },
  { w: "Küche", a: "die", e: "Der neue Herd kommt in die Küche.", t: "kitchen", c: "Wohnen" },
  { w: "Bad", a: "das", e: "Wir haben kein großes Bad.", t: "bathroom", c: "Wohnen" },
  { w: "Balkon", a: "der", e: "Die Wohnung hat einen kleinen Balkon.", t: "balcony", c: "Wohnen" },
  { w: "Garten", a: "der", e: "Wir haben leider keinen Garten.", t: "garden", c: "Wohnen" },
  { w: "Miete", a: "die", e: "Die Miete ist 600 Euro.", t: "rent", c: "Wohnen" },
  { w: "Möbel", a: "die", e: "Sind die Möbel neu?", t: "furniture", c: "Wohnen" },
  { w: "Tisch", a: "der", e: "Die Fotos liegen auf dem Tisch.", t: "table", c: "Wohnen" },
  { w: "Bett", a: "das", e: "Wir brauchen noch ein Kinderbett.", t: "bed", c: "Wohnen" },
  { w: "Schrank", a: "der", e: "Die Gläser stehen im Schrank.", t: "wardrobe / cupboard", c: "Wohnen" },
  { w: "Kühlschrank", a: "der", e: "Die Milch ist im Kühlschrank.", t: "refrigerator", c: "Wohnen" },
  { w: "Schlüssel", a: "der", e: "Ich gebe Ihnen den Zimmerschlüssel.", t: "key", c: "Wohnen" },
  { w: "Aufzug", a: "der", e: "Es gibt keinen Aufzug.", t: "elevator", c: "Wohnen" },
  { w: "Treppe", a: "die", e: "Die Treppe hoch und dann links.", t: "stairs", c: "Wohnen" },

  // Essen
  { w: "Essen", a: "das", e: "Das Essen ist heute sehr gut.", t: "food / meal", c: "Essen" },
  { w: "Frühstück", a: "das", e: "Möchtest du ein Ei zum Frühstück?", t: "breakfast", c: "Essen" },
  { w: "Kaffee", a: "der", e: "Zum Frühstück trinke ich immer Kaffee.", t: "coffee", c: "Essen" },
  { w: "Tee", a: "der", e: "Ich trinke morgens immer Tee.", t: "tea", c: "Essen" },
  { w: "Milch", a: "die", e: "Die Milch steht im Kühlschrank.", t: "milk", c: "Essen" },
  { w: "Wasser", a: "das", e: "Ein Glas Wasser, bitte.", t: "water", c: "Essen" },
  { w: "Bier", a: "das", e: "Noch ein Bier bitte.", t: "beer", c: "Essen" },
  { w: "Wein", a: "der", e: "Ich möchte keinen Wein.", t: "wine", c: "Essen" },
  { w: "Saft", a: "der", e: "Möchtest du einen Apfelsaft?", t: "juice", c: "Essen" },
  { w: "Brot", a: "das", e: "Haben Sie auch Weißbrot?", t: "bread", c: "Essen" },
  { w: "Brötchen", a: "das", e: "Möchtest du Brötchen zum Frühstück?", t: "bread roll", c: "Essen" },
  { w: "Butter", a: "die", e: "Ein Brötchen mit Butter und Käse.", t: "butter", c: "Essen" },
  { w: "Ei", a: "das", e: "Möchtest du ein Ei zum Frühstück?", t: "egg", c: "Essen" },
  { w: "Fleisch", a: "das", e: "Fleisch mag ich nicht.", t: "meat", c: "Essen" },
  { w: "Fisch", a: "der", e: "Ich esse gern Fisch.", t: "fish", c: "Essen" },
  { w: "Reis", a: "der", e: "Ich esse gern Reis.", t: "rice", c: "Essen" },
  { w: "Salat", a: "der", e: "Wie schmeckt dir der Salat?", t: "salad", c: "Essen" },
  { w: "Obst", a: "das", e: "Im Sommer ist das Obst billig.", t: "fruit", c: "Essen" },
  { w: "Gemüse", a: "das", e: "Gemüse brauchen wir auch noch.", t: "vegetables", c: "Essen" },
  { w: "Kartoffel", a: "die", e: "Für Pommes braucht man Kartoffeln.", t: "potato", c: "Essen" },
  { w: "Tomate", a: "die", e: "Die Tomate ist noch grün.", t: "tomato", c: "Essen" },
  { w: "Apfel", a: "der", e: "Ein Pfund Äpfel bitte.", t: "apple", c: "Essen" },
  { w: "Banane", a: "die", e: "Drei Bananen, bitte!", t: "banana", c: "Essen" },
  { w: "Kuchen", a: "der", e: "Ich nehme ein Stück Kuchen.", t: "cake", c: "Essen" },
  { w: "Hähnchen", a: "das", e: "Ein Hähnchen mit Pommes bitte!", t: "chicken", c: "Essen" },
  { w: "Speisekarte", a: "die", e: "Die Speisekarte, bitte.", t: "menu", c: "Essen" },
  { w: "Rechnung", a: "die", e: "Die Rechnung, bitte.", t: "bill / check", c: "Essen" },
  { w: "Restaurant", a: "das", e: "Wir essen heute in einem Restaurant.", t: "restaurant", c: "Essen" },
  { w: "Café", a: "das", e: "Sollen wir uns im Café treffen?", t: "café", c: "Essen" },

  // Einkaufen
  { w: "Geschäft", a: "das", e: "Die Geschäfte schließen um 18.30 Uhr.", t: "shop / store", c: "Einkaufen" },
  { w: "Laden", a: "der", e: "Im Buchladen können Sie Bücher kaufen.", t: "store / shop", c: "Einkaufen" },
  { w: "Kasse", a: "die", e: "Zahlen Sie bitte an der Kasse.", t: "cash register / checkout", c: "Einkaufen" },
  { w: "Preis", a: "der", e: "Die Preise sind hoch.", t: "price", c: "Einkaufen" },
  { w: "Geld", a: "das", e: "Hast du noch Geld?", t: "money", c: "Einkaufen" },
  { w: "billig", a: "", e: "Die Jacke ist aber billig!", t: "cheap", c: "Einkaufen" },
  { w: "teuer", a: "", e: "Das ist mir zu teuer.", t: "expensive", c: "Einkaufen" },
  { w: "kaufen", a: "", e: "Tim kauft sich ein neues Auto.", t: "to buy", c: "Einkaufen" },
  { w: "bezahlen", a: "", e: "Wo muss ich bezahlen?", t: "to pay", c: "Einkaufen" },
  { w: "kosten", a: "", e: "Wie viel kostet das?", t: "to cost", c: "Einkaufen" },

  // Reisen
  { w: "Bahnhof", a: "der", e: "Komme ich hier zum Bahnhof?", t: "train station", c: "Reisen" },
  { w: "Zug", a: "der", e: "Ich fahre gern mit dem Zug.", t: "train", c: "Reisen" },
  { w: "Bus", a: "der", e: "Wann kommt der nächste Bus?", t: "bus", c: "Reisen" },
  { w: "S-Bahn", a: "die", e: "Ich nehme lieber die S-Bahn.", t: "city train / metro", c: "Reisen" },
  { w: "Taxi", a: "das", e: "Er fährt mit dem Taxi.", t: "taxi", c: "Reisen" },
  { w: "Auto", a: "das", e: "Er kommt mit dem Auto.", t: "car", c: "Reisen" },
  { w: "Fahrrad", a: "das", e: "Fährst du mit dem Fahrrad?", t: "bicycle", c: "Reisen" },
  { w: "Flugzeug", a: "das", e: "Das Flugzeug kommt heute später an.", t: "airplane", c: "Reisen" },
  { w: "Flughafen", a: "der", e: "Kannst du mich zum Flughafen bringen?", t: "airport", c: "Reisen" },
  { w: "Haltestelle", a: "die", e: "An der nächsten Haltestelle aussteigen.", t: "bus stop", c: "Reisen" },
  { w: "Fahrkarte", a: "die", e: "Hast du schon eine Fahrkarte?", t: "ticket", c: "Reisen" },
  { w: "Ticket", a: "das", e: "Wie viel kostet das Ticket?", t: "ticket", c: "Reisen" },
  { w: "Gepäck", a: "das", e: "Wollen Sie Ihr Gepäck mitnehmen?", t: "luggage", c: "Reisen" },
  { w: "Koffer", a: "der", e: "Ist das Ihr Koffer?", t: "suitcase", c: "Reisen" },
  { w: "Hotel", a: "das", e: "Im Urlaub sind wir in einem Hotel.", t: "hotel", c: "Reisen" },
  { w: "Reise", a: "die", e: "Wir machen eine Reise nach Österreich.", t: "trip / journey", c: "Reisen" },
  { w: "Urlaub", a: "der", e: "Ich nehme im September Urlaub.", t: "vacation / holiday", c: "Reisen" },
  { w: "Straße", a: "die", e: "In welcher Straße wohnen Sie?", t: "street", c: "Reisen" },

  // Arbeit
  { w: "Arbeit", a: "die", e: "Mein Bruder sucht Arbeit.", t: "work / job", c: "Arbeit" },
  { w: "arbeiten", a: "", e: "Wo arbeiten Sie?", t: "to work", c: "Arbeit" },
  { w: "Beruf", a: "der", e: "Was ist Ihr Beruf?", t: "profession / occupation", c: "Arbeit" },
  { w: "Job", a: "der", e: "Jenny hat einen neuen Job.", t: "job", c: "Arbeit" },
  { w: "Firma", a: "die", e: "Er arbeitet bei einer Firma.", t: "company / firm", c: "Arbeit" },
  { w: "Chef", a: "der", e: "Wir haben eine neue Chefin.", t: "boss", c: "Arbeit" },
  { w: "Kollege", a: "der", e: "Wie heißt die neue Kollegin?", t: "colleague", c: "Arbeit" },
  { w: "Lehrer", a: "der", e: "Unsere Lehrerin heißt Frau Müller.", t: "teacher", c: "Arbeit" },
  { w: "Arzt", a: "der", e: "Ich habe einen Termin beim Arzt.", t: "doctor", c: "Arbeit" },
  { w: "Student", a: "der", e: "Ich bin Studentin.", t: "student", c: "Arbeit" },
  { w: "Termin", a: "der", e: "Machen wir sofort einen Termin.", t: "appointment", c: "Arbeit" },

  // Lernen
  { w: "Schule", a: "die", e: "Meine Tochter geht in die Schule.", t: "school", c: "Lernen" },
  { w: "Kurs", a: "der", e: "Der Deutschkurs geht bis zum Sommer.", t: "course", c: "Lernen" },
  { w: "Unterricht", a: "der", e: "Unterricht von 8 bis 12 Uhr.", t: "class / lesson", c: "Lernen" },
  { w: "Prüfung", a: "die", e: "Die Prüfung ist am Montag.", t: "exam", c: "Lernen" },
  { w: "Test", a: "der", e: "Der Test war einfach.", t: "test", c: "Lernen" },
  { w: "lernen", a: "", e: "Wie lange lernen Sie schon Deutsch?", t: "to learn", c: "Lernen" },
  { w: "Sprache", a: "die", e: "Welche Sprachen sprichst du?", t: "language", c: "Lernen" },

  // Verben
  { w: "gehen", a: "", e: "Ich muss zum Arzt gehen.", t: "to go", c: "Verben" },
  { w: "kommen", a: "", e: "Woher kommen Sie?", t: "to come", c: "Verben" },
  { w: "fahren", a: "", e: "Ich fahre mit dem Auto zur Arbeit.", t: "to drive / travel", c: "Verben" },
  { w: "machen", a: "", e: "Was machst du heute Abend?", t: "to do / make", c: "Verben" },
  { w: "sprechen", a: "", e: "Kann ich mit Herrn Klein sprechen?", t: "to speak", c: "Verben" },
  { w: "schreiben", a: "", e: "Er schreibt jeden Tag E-Mails.", t: "to write", c: "Verben" },
  { w: "lesen", a: "", e: "Ich lese ein Buch.", t: "to read", c: "Verben" },
  { w: "hören", a: "", e: "Hör mal! Was ist das?", t: "to hear / listen", c: "Verben" },
  { w: "sehen", a: "", e: "Ich kann dich nicht sehen.", t: "to see", c: "Verben" },
  { w: "essen", a: "", e: "Was gibt es zu essen?", t: "to eat", c: "Verben" },
  { w: "trinken", a: "", e: "Möchtest du etwas trinken?", t: "to drink", c: "Verben" },
  { w: "schlafen", a: "", e: "Ich schlafe acht Stunden.", t: "to sleep", c: "Verben" },
  { w: "wohnen", a: "", e: "Ich wohne in München.", t: "to live", c: "Verben" },
  { w: "helfen", a: "", e: "Können Sie mir helfen?", t: "to help", c: "Verben" },
  { w: "brauchen", a: "", e: "Brauchst du die Zeitung noch?", t: "to need", c: "Verben" },
  { w: "möchten", a: "", e: "Was möchten Sie trinken?", t: "would like", c: "Verben" },
  { w: "können", a: "", e: "Ich kann Deutsch und Russisch.", t: "can / to be able to", c: "Verben" },
  { w: "müssen", a: "", e: "Ich muss von 8 bis 18 Uhr arbeiten.", t: "must / to have to", c: "Verben" },
  { w: "sollen", a: "", e: "Was soll ich mitbringen?", t: "should / to be supposed to", c: "Verben" },
  { w: "dürfen", a: "", e: "Sie dürfen hier nicht rauchen.", t: "may / to be allowed to", c: "Verben" },
  { w: "wollen", a: "", e: "Wollen Sie einen Kaffee?", t: "to want", c: "Verben" },
  { w: "kennen", a: "", e: "Kennen Sie diese Frau?", t: "to know (a person)", c: "Verben" },
  { w: "wissen", a: "", e: "Weißt du, wie er heißt?", t: "to know (a fact)", c: "Verben" },
  { w: "nehmen", a: "", e: "Ich nehme den Bus.", t: "to take", c: "Verben" },
  { w: "geben", a: "", e: "Geben Sie mir bitte den Kugelschreiber.", t: "to give", c: "Verben" },
  { w: "stehen", a: "", e: "Der Bus steht an der Haltestelle.", t: "to stand", c: "Verben" },
  { w: "kochen", a: "", e: "Herr Georgi kann gut kochen.", t: "to cook", c: "Verben" },
  { w: "spielen", a: "", e: "Die Kinder spielen draußen.", t: "to play", c: "Verben" },
  { w: "schwimmen", a: "", e: "Ich schwimme jeden Tag.", t: "to swim", c: "Verben" },
  { w: "beginnen", a: "", e: "Das Spiel beginnt um 15.30 Uhr.", t: "to begin / start", c: "Verben" },
  { w: "aufstehen", a: "", e: "Ich muss um vier Uhr aufstehen.", t: "to get up", c: "Verben" },
  { w: "anrufen", a: "", e: "Kann man Sie anrufen?", t: "to call", c: "Verben" },
  { w: "einkaufen", a: "", e: "Ich muss noch einkaufen.", t: "to go shopping", c: "Verben" },
  { w: "verstehen", a: "", e: "Können Sie mich verstehen?", t: "to understand", c: "Verben" },

  // Adjektive
  { w: "gut", a: "", e: "Das finde ich gut.", t: "good", c: "Adjektive" },
  { w: "schlecht", a: "", e: "Mir ist schlecht!", t: "bad", c: "Adjektive" },
  { w: "schön", a: "", e: "Das ist sehr schön.", t: "beautiful / nice", c: "Adjektive" },
  { w: "groß", a: "", e: "Frankfurt ist eine große Stadt.", t: "big / tall", c: "Adjektive" },
  { w: "klein", a: "", e: "Eltville ist eine kleine Stadt.", t: "small / little", c: "Adjektive" },
  { w: "alt", a: "", e: "Wie alt sind Sie?", t: "old", c: "Adjektive" },
  { w: "neu", a: "", e: "Ich bin der neue Kollege.", t: "new", c: "Adjektive" },
  { w: "jung", a: "", e: "Noch so jung?", t: "young", c: "Adjektive" },
  { w: "schnell", a: "", e: "Er fährt schnell.", t: "fast / quick", c: "Adjektive" },
  { w: "langsam", a: "", e: "Bitte etwas langsamer sprechen.", t: "slow", c: "Adjektive" },
  { w: "leicht", a: "", e: "Der Koffer ist leicht.", t: "light / easy", c: "Adjektive" },
  { w: "schwer", a: "", e: "Ist Ihr Gepäck sehr schwer?", t: "heavy / difficult", c: "Adjektive" },
  { w: "krank", a: "", e: "Ich bin krank.", t: "sick / ill", c: "Adjektive" },
  { w: "müde", a: "", e: "Ich bin müde.", t: "tired", c: "Adjektive" },
  { w: "frei", a: "", e: "Ist der Platz noch frei?", t: "free / available", c: "Adjektive" },
  { w: "richtig", a: "", e: "Das ist richtig.", t: "right / correct", c: "Adjektive" },
  { w: "falsch", a: "", e: "Das ist falsch.", t: "wrong / false", c: "Adjektive" },
  { w: "einfach", a: "", e: "Die Prüfung ist ganz einfach.", t: "simple / easy", c: "Adjektive" },
  { w: "wichtig", a: "", e: "Dieses Formular ist sehr wichtig.", t: "important", c: "Adjektive" },
  { w: "kaputt", a: "", e: "Das Glas ist kaputt.", t: "broken", c: "Adjektive" },
  { w: "fertig", a: "", e: "Bist du fertig?", t: "ready / done", c: "Adjektive" },
  { w: "laut", a: "", e: "Nicht so laut! Das Baby schläft.", t: "loud / noisy", c: "Adjektive" },
  { w: "ruhig", a: "", e: "Ich möchte ein ruhiges Zimmer.", t: "quiet / calm", c: "Adjektive" },

  // Kommunikation
  { w: "Hallo", a: "", e: "Hallo! Wie geht's?", t: "hello", c: "Kommunikation" },
  { w: "Guten Morgen", a: "", e: "Guten Morgen!", t: "good morning", c: "Kommunikation" },
  { w: "Guten Tag", a: "", e: "Guten Tag, Herr Sommer!", t: "good day / hello", c: "Kommunikation" },
  { w: "Auf Wiedersehen", a: "", e: "Auf Wiedersehen!", t: "goodbye", c: "Kommunikation" },
  { w: "Tschüss", a: "", e: "Tschüss! Bis morgen!", t: "bye", c: "Kommunikation" },
  { w: "Danke", a: "", e: "Vielen Dank!", t: "thank you", c: "Kommunikation" },
  { w: "Bitte", a: "", e: "Eine Tasse Kaffee, bitte!", t: "please / you're welcome", c: "Kommunikation" },
  { w: "Entschuldigung", a: "die", e: "Entschuldigung! – Bitte.", t: "excuse me / sorry", c: "Kommunikation" },
  { w: "ja", a: "", e: "Ja.", t: "yes", c: "Kommunikation" },
  { w: "nein", a: "", e: "Nein, ich habe keine Zeit.", t: "no", c: "Kommunikation" },
  { w: "Hilfe", a: "die", e: "Hilfe! Bitte helfen Sie mir!", t: "help", c: "Kommunikation" },

  // Orte
  { w: "Stadt", a: "die", e: "Heidelberg ist eine alte Stadt.", t: "city / town", c: "Orte" },
  { w: "Post", a: "die", e: "Wo ist die Post, bitte?", t: "post office", c: "Orte" },
  { w: "Bank", a: "die", e: "Die Bank schließt um vier Uhr.", t: "bank", c: "Orte" },
  { w: "Polizei", a: "die", e: "Holen Sie die Polizei!", t: "police", c: "Orte" },
  { w: "Kino", a: "das", e: "Wir sehen im Kino einen Film.", t: "cinema / movie theater", c: "Orte" },
  { w: "Bäckerei", a: "die", e: "Ich geh zur Bäckerei.", t: "bakery", c: "Orte" },
  { w: "Kindergarten", a: "der", e: "Laura geht in den Kindergarten.", t: "kindergarten / preschool", c: "Orte" },
  { w: "Schwimmbad", a: "das", e: "Kommst du mit ins Schwimmbad?", t: "swimming pool", c: "Orte" },

  // Gesundheit
  { w: "Kopf", a: "der", e: "Mein Kopf tut weh!", t: "head", c: "Gesundheit" },
  { w: "Auge", a: "das", e: "Er hat blaue Augen.", t: "eye", c: "Gesundheit" },
  { w: "Hand", a: "die", e: "Er gibt mir die Hand.", t: "hand", c: "Gesundheit" },
  { w: "Arm", a: "der", e: "Mein Arm tut weh.", t: "arm", c: "Gesundheit" },
  { w: "Bein", a: "das", e: "Mein rechtes Bein tut weh.", t: "leg", c: "Gesundheit" },
  { w: "Fuß", a: "der", e: "Der linke Fuß tut mir weh.", t: "foot", c: "Gesundheit" },
  { w: "Bauch", a: "der", e: "Mein Bauch tut weh.", t: "stomach / belly", c: "Gesundheit" },
  { w: "Hunger", a: "der", e: "Ich habe Hunger!", t: "hunger", c: "Gesundheit" },
  { w: "Durst", a: "der", e: "Ich habe großen Durst.", t: "thirst", c: "Gesundheit" },
  { w: "Doktor", a: "der", e: "Wir gehen zum Doktor.", t: "doctor", c: "Gesundheit" },

  // Technik
  { w: "Telefon", a: "das", e: "Haben Sie Telefon?", t: "telephone", c: "Technik" },
  { w: "Handy", a: "das", e: "Bitte die Handys ausmachen!", t: "mobile phone", c: "Technik" },
  { w: "Computer", a: "der", e: "Wann bekommst du deinen Computer?", t: "computer", c: "Technik" },
  { w: "Internet", a: "das", e: "Das findest du im Internet.", t: "internet", c: "Technik" },
  { w: "E-Mail", a: "die", e: "Ich habe Ihre E-Mail nicht bekommen.", t: "email", c: "Technik" },
  { w: "Brief", a: "der", e: "Haben Sie einen Brief für mich?", t: "letter", c: "Technik" },
  { w: "Zeitung", a: "die", e: "Ich lese gern Zeitung.", t: "newspaper", c: "Technik" },
  { w: "Foto", a: "das", e: "Darf ich ein Foto machen?", t: "photo", c: "Technik" },
  { w: "Buch", a: "das", e: "Gute Bücher sind oft teuer.", t: "book", c: "Technik" },

  // Kleidung
  { w: "Kleidung", a: "die", e: "Wo finde ich Kleidung?", t: "clothing / clothes", c: "Kleidung" },
  { w: "Jacke", a: "die", e: "Zieh dir eine Jacke an!", t: "jacket", c: "Kleidung" },
  { w: "Schuh", a: "der", e: "Zieh die Schuhe aus!", t: "shoe", c: "Kleidung" },

  // Wetter
  { w: "Wetter", a: "das", e: "Wir hatten schlechtes Wetter.", t: "weather", c: "Wetter" },
  { w: "Regen", a: "der", e: "Bei diesem Regen gehe ich nicht raus.", t: "rain", c: "Wetter" },
  { w: "Sonne", a: "die", e: "Die Sonne scheint.", t: "sun", c: "Wetter" },
  { w: "kalt", a: "", e: "Mir ist kalt.", t: "cold", c: "Wetter" },
  { w: "warm", a: "", e: "Es ist warm heute.", t: "warm", c: "Wetter" },

  // Sonstiges
  { w: "aber", a: "", e: "Ich bin oft im Büro, aber nur kurz.", t: "but", c: "Sonstiges" },
  { w: "auch", a: "", e: "Ich bin auch Spanier.", t: "also / too", c: "Sonstiges" },
  { w: "dann", a: "", e: "Erst zur Post, dann komme ich.", t: "then", c: "Sonstiges" },
  { w: "gern(e)", a: "", e: "Ich gehe gerne einkaufen.", t: "gladly / with pleasure", c: "Sonstiges" },
  { w: "heute", a: "", e: "Heute ist ein schöner Tag.", t: "today", c: "Sonstiges" },
  { w: "hier", a: "", e: "Hier wohne ich.", t: "here", c: "Sonstiges" },
  { w: "immer", a: "", e: "Sie kommt immer zu spät.", t: "always", c: "Sonstiges" },
  { w: "jetzt", a: "", e: "Jetzt machen wir Pause.", t: "now", c: "Sonstiges" },
  { w: "morgen", a: "", e: "Morgen beginnt die Schule.", t: "tomorrow", c: "Sonstiges" },
  { w: "gestern", a: "", e: "Gestern war ich krank.", t: "yesterday", c: "Sonstiges" },
  { w: "nicht", a: "", e: "Das stimmt nicht.", t: "not", c: "Sonstiges" },
  { w: "noch", a: "", e: "Wir warten noch fünf Minuten.", t: "still / yet", c: "Sonstiges" },
  { w: "nur", a: "", e: "Ich möchte nur ein Glas Wasser.", t: "only / just", c: "Sonstiges" },
  { w: "sehr", a: "", e: "Danke sehr!", t: "very", c: "Sonstiges" },
  { w: "viel", a: "", e: "Hier regnet es viel.", t: "much / many", c: "Sonstiges" },
  { w: "zusammen", a: "", e: "Sollen wir zusammen essen gehen?", t: "together", c: "Sonstiges" },
  { w: "rechts", a: "", e: "Die Straße ist hier rechts.", t: "right", c: "Sonstiges" },
  { w: "links", a: "", e: "Gehen Sie die nächste Straße links.", t: "left", c: "Sonstiges" },
  { w: "geradeaus", a: "", e: "Gehen Sie immer geradeaus!", t: "straight ahead", c: "Sonstiges" },
  { w: "Deutschland", a: "", e: "Ich wohne in Deutschland.", t: "Germany", c: "Sonstiges" },
  { w: "Formular", a: "das", e: "Füllen Sie dieses Formular aus.", t: "form", c: "Sonstiges" },
  { w: "Ausweis", a: "der", e: "Hier ist mein Ausweis.", t: "ID card", c: "Sonstiges" },
  { w: "Hobby", a: "das", e: "Meine Hobbys sind Wandern und Schwimmen.", t: "hobby", c: "Sonstiges" },
  { w: "Sport", a: "der", e: "Ich mache viel Sport.", t: "sport", c: "Sonstiges" },
  { w: "Fußball", a: "der", e: "Spielt ihr gerne Fußball?", t: "football / soccer", c: "Sonstiges" },
  { w: "Geschenk", a: "das", e: "Danke für das schöne Geschenk.", t: "gift / present", c: "Sonstiges" },
  { w: "Einladung", a: "die", e: "Danke für die Einladung!", t: "invitation", c: "Sonstiges" },
];

export const emailPrompts = [
  {
    scenario: "Ihr Freund Thomas lädt Sie per E-Mail zu seiner Geburtstagsparty ein.",
    instruction: "Schreiben Sie Thomas eine Antwort. Schreiben Sie zu drei Punkten:",
    points: ["Dank für die Einladung", "kommen Sie? (wann?)", "was bringen Sie mit?"],
  },
  {
    scenario: "Sie haben einen Arzttermin am Montag um 10 Uhr, können aber nicht kommen.",
    instruction: "Schreiben Sie dem Arzt eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Entschuldigung — warum können Sie nicht kommen?", "bitten Sie um einen neuen Termin", "wann haben Sie Zeit?"],
  },
  {
    scenario: "Sie möchten einen Deutschkurs machen. Sie haben die Webseite einer Sprachschule gefunden.",
    instruction: "Schreiben Sie der Sprachschule eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Wann beginnt der Kurs?", "wie viel kostet er?", "gibt es noch freie Plätze?"],
  },
  {
    scenario: "In Ihrer Wohnung ist die Heizung kaputt. Es ist sehr kalt.",
    instruction: "Schreiben Sie Ihrem Vermieter eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Problem beschreiben", "seit wann ist die Heizung kaputt?", "bitten Sie um schnelle Hilfe"],
  },
  {
    scenario: "Ihre Freundin Mia hat Ihnen ein Geschenk zum Geburtstag geschickt.",
    instruction: "Schreiben Sie Mia eine Antwort. Schreiben Sie zu drei Punkten:",
    points: ["Dank für das Geschenk", "wie finden Sie es?", "laden Sie Mia zum Kaffee ein"],
  },
  {
    scenario: "Sie möchten die Prüfung Goethe-Zertifikat A1 ablegen.",
    instruction: "Schreiben Sie dem Goethe-Institut eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["wann findet die Prüfung statt?", "wie viel kostet die Anmeldung?", "wie können Sie sich anmelden?"],
  },
  {
    scenario: "Sie möchten Ihren Kollegen Leon nach der Arbeit zum Kaffee einladen.",
    instruction: "Schreiben Sie Leon eine kurze Nachricht. Schreiben Sie zu drei Punkten:",
    points: ["Einladung (wann und wohin?)", "warum möchten Sie sich treffen?", "bitten Sie um eine Antwort"],
  },
  {
    scenario: "Ihr Kind ist krank und kann heute nicht in die Schule gehen.",
    instruction: "Schreiben Sie der Lehrerin eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Ihr Kind kommt heute nicht", "warum? (was ist das Problem?)", "wann kommt es wieder?"],
  },
  {
    scenario: "Sie möchten ins Schwimmbad gehen und haben Fragen.",
    instruction: "Schreiben Sie dem Schwimmbad eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Wann hat das Schwimmbad geöffnet?", "was kostet der Eintritt?", "gibt es Kurse für Erwachsene?"],
  },
  {
    scenario: "Sie kommen zu einem Treffen mit Ihrem Freund Felix zu spät.",
    instruction: "Schreiben Sie Felix eine kurze Nachricht. Schreiben Sie zu drei Punkten:",
    points: ["Entschuldigung — Sie kommen zu spät", "warum?", "wann kommen Sie an?"],
  },
  {
    scenario: "Sie möchten ein Hotelzimmer für Ihren Urlaub buchen.",
    instruction: "Schreiben Sie dem Hotel eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["wann möchten Sie kommen? (wie viele Nächte?)", "Einzel- oder Doppelzimmer?", "was kostet das Zimmer? (mit Frühstück?)"],
  },
  {
    scenario: "Sie haben eine neue Wohnung und möchten Ihren Freund Ben einladen.",
    instruction: "Schreiben Sie Ben eine E-Mail. Schreiben Sie zu drei Punkten:",
    points: ["Beschreibung der Wohnung (Zimmer, Lage)", "was gefällt Ihnen an der Wohnung?", "laden Sie Ben zur Besichtigung ein"],
  },
];

export const wfQuestions = [
  { q: "___ heißen Sie?", a: "Wie", o: ["Wo", "Wie", "Was", "Wann"] },
  { q: "___ wohnen Sie?", a: "Wo", o: ["Wer", "Was", "Wo", "Warum"] },
  { q: "___ kommen Sie?", a: "Woher", o: ["Woher", "Wohin", "Wo", "Wann"] },
  { q: "___ beginnt der Kurs?", a: "Wann", o: ["Was", "Wo", "Wann", "Wer"] },
  { q: "___ kostet das?", a: "Wie viel", o: ["Was", "Wie viel", "Wann", "Wo"] },
  { q: "___ ist das?", a: "Wer", o: ["Wer", "Wo", "Was", "Wie"] },
  { q: "___ lernst du Deutsch?", a: "Warum", o: ["Wann", "Warum", "Wie", "Wo"] },
  { q: "___ fährst du am Wochenende?", a: "Wohin", o: ["Woher", "Wo", "Wann", "Wohin"] },
  { q: "___ Sprachen sprechen Sie?", a: "Welche", o: ["Was", "Welche", "Wie", "Wann"] },
  { q: "___ alt sind Sie?", a: "Wie", o: ["Was", "Wo", "Wie", "Wer"] },
  { q: "___ machst du heute?", a: "Was", o: ["Wer", "Was", "Wo", "Wann"] },
  { q: "___ geht es Ihnen?", a: "Wie", o: ["Wie", "Was", "Wo", "Wer"] },
  { q: "___ kommt der nächste Bus?", a: "Wann", o: ["Wo", "Wann", "Was", "Wer"] },
  { q: "___ ist die Toilette?", a: "Wo", o: ["Was", "Wer", "Wo", "Wie"] },
  { q: "___ möchten Sie trinken?", a: "Was", o: ["Wie", "Was", "Wo", "Wer"] },
  { q: "___ Kinder haben Sie?", a: "Wie viele", o: ["Was", "Wann", "Wie viele", "Welche"] },
  { q: "___ ist Ihr Beruf?", a: "Was", o: ["Wer", "Was", "Wie", "Wann"] },
  { q: "___ Buch möchtest du?", a: "Welches", o: ["Was", "Welches", "Wie", "Wo"] },
  { q: "___ kommt er nicht?", a: "Warum", o: ["Wann", "Warum", "Wie", "Wo"] },
];

export const schedule = [
  { d: 1, f: "Decoding", t: "Go through flashcards. Mark words you don't know." },
  { d: 2, f: "Decoding", t: "Continue flashcards. Focus on 'Don't Know' words." },
  { d: 3, f: "Decoding", t: "Final pass through unknown words. Use Word List to review." },
  { d: 4, f: "Patterns", t: "Study Grammar tab. Watch A1 Speaking Exam videos on YouTube." },
  { d: 5, f: "Patterns", t: "Practice Speaking Simulator. Note exact phrases." },
  { d: 6, f: "Patterns", t: "Master W-Fragen quiz. Review email templates." },
  { d: 7, f: "Simulations", t: "Do practice test set 1 (Goethe website). Time yourself." },
  { d: 8, f: "Simulations", t: "Do practice test set 2. Review mistakes." },
  { d: 9, f: "Simulations", t: "Do practice test set 3. Focus on listening (catch the nouns!)." },
  { d: 10, f: "Simulations", t: "Review all wrong answers. Drill weak categories." },
  { d: 11, f: "Production", t: "Write 2 practice emails. Self-Intro 5 times." },
  { d: 12, f: "Production", t: "Write 2 more emails. Self-Intro 5 more times. Speaking cards." },
  { d: 13, f: "Production", t: "Final email. Self-Intro 10 times. Full speaking run-through." },
  { d: 14, f: "Rest", t: "Review Grammar cheat sheet & email templates only. You got this." },
];
